### ISSUE TITLE
Table update or fireTableDataChanged() should be suspended when pausing

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#13]
Created: 2014-12-08
Migrated from https://sourceforge.net/p/mars-sim/tickets/24/

I notice on every TableModel, fireTableDataChanged() is called to update each cell on the Jtable. This happens even when I intentionally pause the simulation.

It consumes unnecessary cpu cycle and can potentially lead to problems in computing values that are time based.

Question : can we put the table update on a separate thread and can this thread be suspended safely?

On UnitWindow.java line 143-148:
```
    public void update() {
        // Update each of the tab panels.
        for (TabPanel tabPanel : tabPanels) {
           tabPanel.update();
        }
    }
```
It seems every tabPanel got this update even when I pause the simulation.
Note that there are at least two cases when the simulation is paused:

1. user clicks on the pause on the time tool
2. computer goes into a power saving mode dictated by the cpu

**Comment by mokun** [comment]
This issue has been taken care of as of many builds ago. We have since switched to using UnitWindowTask's run() in line 1172 in MainDesktopPane to call update() in UnitWindow. 

`
	class UnitWindowTask implements Runnable {
		UnitWindow unitWindow;

		private UnitWindowTask(UnitWindow unitWindow) {
			this.unitWindow = unitWindow;
		}

		@Override
		public void run() {
			unitWindow.update();
		}
	}
`

When mars-sim is put on pause, MasterClock no longer calls clockPulse(). This halts calling update() in MainDesktopPane, which in turn stop calling runUnitWindowExecutor(), which in turns halt the runnable task of UnitWindowTask.

**Comment by mokun** [comment]
Resolved
