### ISSUE TITLE
 Truncated hallway

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#15]
Created: 2014-12-15
Migrated over from: https://sourceforge.net/p/mars-sim/tickets/28/ 

I have two truncated hallways.
1. The lounge was relocated to the bottom
2. The C2 building was between the top lander hab and the residential quarter but was NOT popped into the "correct" grid.
3. The two hallways to the left and the right of the C2 building could NOT be stretched all the way to seamlessly connect the C2 building to the adjacent building.

![truncated hallway](https://cloud.githubusercontent.com/assets/7767079/22947978/2b43208e-f2fd-11e6-8529-f153d52d0c17.png)

**Comment by mokun** [comment]
Already fixed the issue of mis-replaceing of the C2 building. It can lie up pretty well with the two adjacent hallways. 

However, we need to rework the algorithm responsible for stretching and shrinking the hallway and the placing the end caps since it fails from time to time under the new Transport Wizard.

**Comment by mokun** [comment]
This problem is NOT seen any more in recent build. In 3.1.0-p7, the Transport/Construction Wizard have been disabled to avoid certain unresolved issues. Closed.
