### ISSUE TITLE
Missions not working - flag won't move

### ISSUE THREAD

**Issue by EmilPetecki** [mars-sim/mars-sim#196]
**Describe the bug/issue**
 - Flag dragging in the mission menu is not working. 

**Affected Area**
 - Mission menu

**Expected behaviors**
 - I'm expecting the flag to move when I click and drag it, but it does not. 

**Actual/Observed Behaviors**
 - When I'm clicking the flag, it turns green, but dragging it accomplishes nothing. Sometimes, though, the flag will not turn green at all. 

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : Java 10.0.2
 - mars-sim build version : the latest stable version

**Comment by mokun** [comment]
Hi @EmilPetecki , 

Do you mean you discover this issue when running version 3.1.0-b1 or Build 4945 ?

**Comment by EmilPetecki** [comment]
3.1.0-b1

**Comment by mokun** [comment]
@EmilPetecki ,

Are you on an Exploration Mission ?

**Comment by mokun** [comment]
Last time we dealt with a similar issue with flag dragging and it was fixed [here](https://github.com/mars-sim/mars-sim/commit/4fe10ec901344eb34a62c688e4bd977d86b3a039).

**Comment by mokun** [comment]
@EmilPetecki , 

The mechanics of the game is that if you want to start a *Mining* mission, it will first retrieve a list of *Explored Sites* and let you choose one or more sites for your Mining mission.

However, you may have ZERO explored sites on file, especially if you haven't started an *Exploration* mission yet.

> Note that the simulation is smart enough to automatically start Exploration missions if enough resources are available in a settlement.

However, if you only have ONE explored site that is suitable for mining, you will not be allowed to drag or move the flag, because that was the only coordinate that you can select for that Mining mission.

I wonder if this is the scenario you happen to run into and do let me know.

Meanwhile, do check out the latest build at https://github.com/mars-sim/mars-sim/releases . 

Appreciate for your support !

**Comment by mokun** [comment]
Fixed.
