### ISSUE TITLE
Design Idea: Adopt Kotlin

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#197]
[Kotlin](https://kotlinlang.org/) has been gaining popularity in recent years. 

It's a more concise language than Java, more inoperable, is safer and supposedly more tool friendly.

It is fully compatible with existing Java stacks and having a smooth learning curve for Java programmer.

Kotlin language has many neat features that Java lacks and should increases the developers' productivity.

Recently, Kotlin has become Google’s preferred language for Android app development in *Android Studio*.

So it's about time we integrate the capability of coding in Kotlin for mars-sim. This [page](https://www.zoftino.com/creating-kotlin-jar-using-maven-in-eclipse) shows how to configure maven to compile kotlin code into java.

For sure, IntelliJ IDE is already kotlin-feature ready. 

But, in case of Eclipse IDE, developer may install [kotlin plug-in](https://kotlinlang.org/docs/tutorials/getting-started-eclipse.html) in Eclipse Marketplace.

**Comment by Urwumpe** [comment]
I doubt a programming language change fixes problems. Especially, it is a much more difficult transition than any API change in Java. 

I could imagine mixing new Kotlin modules with older Java modules in MSP, but again, I doubt the big picture of the programming language fixes problems we have at the domain specific language level. Those would persist, regardless which syntax we use. 

We should focus on making the existing core modules rock solid and maybe then move things slowly into newer possibly kotlin modules. But IMHO, it would be better to keep using Java for the core - especially because of the existing code.

**Comment by mokun** [comment]
> I doubt a programming language change fixes problems

True that kotlin won't magically fix any existing problems by itself.

It does open up new [possibilities](https://github.com/KotlinBy/awesome-kotlin) :D

I plan to use [TornadoFX](https://github.com/edvin/tornadofx) with JavaFX in kotlin.

See also [this](https://www.kotlindevelopment.com/super-productive-native/).

**Comment by Urwumpe** [comment]
Either I am getting blind or I don't see any big change there to Java ... just some syntactic sugars, but the same code, still not the big improvement. 

Well, the more UI modules, the merrier, right? But what about moving the UI into a web-browser? We could do some great stuff with WebGL as well.

**Comment by larsnaesbye** [comment]
Kotlin brings one important thing to the table and that’s null safety. In large projects like mars-sim this can be useful. I started a discussion before rediscovering this issue.

**Comment by bevans2000** [comment]
Project Valhalla is proposing a solid change to null values. I believe sticking with Java is best.
