### ISSUE TITLE
Only one crew member doing all the prep work in mission, Resource Set, Mission Planning, Priority Message Queue, Communication Channel

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#20]
Created: 2015-03-10
Migrated from https://sourceforge.net/p/mars-sim/tickets/58/

Tested on build 3255
Observations:
1. Dream Chaser had 4 crew and still in the Garage
2. Criselda Kendzierski was the only one helping with loading resources
3. The other three were busy with their own tasks and did not seem "prepared" for the trip. They only joined in until the last moment. e.g Patrick O'hara was still sleeping.

Suggestions:
1. We can make use of the Command and Control Center building to stage a mission briefing prior to the preparation stage such as loading resources.
2. Having all of them together in one place prior to preparing for departure simulates what we will be doing in the real world under normal circumstances.
3. In future as we code in a personal schedule/calender for every settler, the mission briefing/unbriefing will be an agenda item for the expedition crew.
4. We can further simulate the new tasks such as programming the rover with gps coordinate, uploading/downloading maps. They can be done by any engineer but the crew members must be involved.
5. Ideally, all crew members should be involved in the preparation for departure. not just selecting the one with highest Strength attribute to load things up.
6. If there is no command and control center, they can still gather in the garage or a lander hab but the logistical "efficiency" of certain follow-on tasks such as loading resources will be lower.

![dream chaser embarking from alpha base](https://cloud.githubusercontent.com/assets/7767079/22948615/7b88508a-f2ff-11e6-88f0-5660d4c46991.png)

**Comment by mokun** [comment]
Will need to create a set of Meta Tasks and Tasks in future to further logically refine what mission planning on Mars should look like.

**Comment by Urwumpe** [comment]
That is what I was also up to with the refactoring of the mission system. Some thoughts that I had last weekend while trying to describe the planning considerations in XML: 

I want to describe the required resources for a mission in a resource set, which also contains variables that describe when and for how long the resources will be reserved. The key idea behind having resource sets is having a way to describe for a settlement, when a mission can be started - even when a mission is a good idea right now, it might not be smart to start it now. Also, it would give the simulated Person doing the planning based on a mission template an object to store the results of his planning work. Also, when loading the rover, all tasks for loading the rover could be created straight from the resource set, so loading the rover would be just picking the next task from the mission backlog until all loading tasks are done.

I already found one communication feature that might be good to have there to implement such a system: Could settlers get a priority queue for messages? If they have one, we could for example trigger special tasks by sending the members of a mission a message from the mission commander. 

If settlements could get a message queue as well, it could also be easier to handle emergency missions. Instead of directly creating the mission, a distressed rover could send a message to the nearest settlements to request a rescue mission.

**Comment by mokun** [comment]
@Urwumpe. 

Very thoughtful comments above and I especially like the idea of message queue for simulating proper communication channels.

There's already a lot of automation in the core engine. 

Passing messages between settlers, vehicles and settlements would need to be more organized.

It would be a very nice feature to be added. Should it be done within or apart from [HistoricalManager](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/events/HistoricalEventManager.java), which has been used for keeping track of events (as well as a few other class that inherit HistoricalEventManager) ?

**Comment by mokun** [comment]
@Urwumpe, feel free to expand the wiki page [Communication Channel](https://github.com/mars-sim/mars-sim/wiki/Communication-Channels).

**Comment by mokun** [comment]
We have since added mission approval & review process, add some pre-mission planning activities such as analyzing site collection rate, etc.

We haven't improved the message queue/communication channel aspects though but we can open a new thread to discuss how to do it.
  
Closing this old thread now.
