### ISSUE TITLE
Is there a way to have a crew profile saved as well, new /xml folder, edit people.xml, new crew.xml, beta_crew.xml

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#207]
Similar to the commander profile, maybe there could be a custom crew profile. As of right now, I do not see a crew profile, for e.g. if I want to have a crew which is all Indian.

**Comment by mokun** [comment]
It's inside [people.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/people.xml)

**Comment by mokun** [comment]
See inside the tag <person-list> below : 

https://github.com/mars-sim/mars-sim/blob/0773c4b272a9120abeb44864e3854d0dca1288d9/mars-sim-core/src/main/resources/conf/people.xml#L3223-L3402

**Comment by mokun** [comment]
We could give the `Crew Editor` the ability to save the modified roster in near future, instead of having to modify the xml file.

**Comment by shirishag75** [comment]
That would be nice. It is better to have the hardcoded values as it and have something which could be modified by the user/gamer while letting the hardcoded values be as it is.

**Comment by mokun** [comment]
Yes. Currently, it's not that convenient for non-technical users to locate and edit the xml files from inside a jar file.

So we will copy the resources folder that stores all the xml files from within the `mars-sim-core-${VERSION}.jar` file to a particular folder in user home so that at the start of every simulation, it will load the xml files from there.

This way, users will be able to directly manipulate the xml files.

This is just the first step.

Next, it makes sense to let users save what they have previously modified in the crew roster and load the same crew roster when starting a new simulation.

**Comment by shirishag75** [comment]
that would make it whole lot of easier. Also I dunno what or how different attributes, traits in people help or not. I can see the attributes but don't know if the interaction between say an introvert and an extrovert or between two introverts or extroverts has some kind of positive or negative results etc.

**Comment by mokun** [comment]
> but don't know if the interaction between say an introvert and an extrovert or between two introverts or extroverts has some kind of positive or negative results etc.

Exactly how we apply the specific nuances of a personality in certain cases are currently all hardcoded within numerous class and methods.

For instance, the high `Neuroticism` score of a person's `Personality Trait` would mean an increase of the probability of an malfunction. That's because he/she is more prone to accident.

**Comment by mokun** [comment]
@shirishag75 

I just relocated all the xml files in the [latest build](https://github.com/mars-sim/mars-sim/commit/81635d7ae179365ed5914d0e161bc3509d0c50a4).

Now you can find them in the /.mars-sim/conf directory within your home folder in Windows OS.

Note that I probably need to consider what home folder is for linux.

Q: Since you are in linux platform, can you cut and paste here the absolute path of where you would find the /.mars-sim/conf directory ? 

e.g. In my Win 10 machine, the xml files are now found at `C:\Users\mk\.mars-sim\conf\` after running mars-sim at least once.

Thanks !

**Comment by mokun** [comment]
We're adding a check box in the `Simulation Configuration Editor (SCE)` called `Load Alpha Crew`. 

If checked, the new simulation will load the `Alpha Crew` as defined in `people.xml`.
If unchecked, the new simulation will not load the `Alpha Crew`.

**Comment by mokun** [comment]
If you are using the *Console Edition* of mars-sim, you can also enable/disable loading the `Alpha Crew` in the menu choice in both the `Command Mode` or the `Sandbox Mode`.

**Comment by shirishag75** [comment]
> @shirishag75
> 
> I just relocated all the xml files in the [latest build](https://github.com/mars-sim/mars-sim/commit/81635d7ae179365ed5914d0e161bc3509d0c50a4).
> 
> For Windows OS, one can find them in the `/.mars-sim/conf/` directory within his home folder.
> 
> Note that I probably need to consider what home folder is for linux.
> 
> Q: Since you are in linux platform, can you cut and paste here the absolute path of where you would find the `/.mars-sim/conf/` directory ?
> 
> e.g. In my Win 10 machine, the xml files are now found at `C:\Users\mk\.mars-sim\conf\` after running mars-sim at least once.
> 
> Thanks !

Seems I missed that - 

Here you go - 

```
:~/.mars-sim/conf$ pwd
/home/shirish/.mars-sim/conf
```

**Comment by shirishag75** [comment]
> If you are using the _Console Edition_ of mars-sim, you can also enable/disable loading the `Alpha Crew` in the menu choice in both the `Command Mode` or the `Sandbox Mode`.

how ?

**Comment by mokun** [comment]
Please delete the `/conf` directory, it's NO LONGER being used.

**Comment by mokun** [comment]
The Alpha Crew is located in the section called <person-list>in `people.xml`

See below : 
https://github.com/mars-sim/mars-sim/blob/1fb282350d0015a69faee9daa31c574790a57097/mars-sim-core/src/main/resources/xml/people.xml#L3342-L3521

In the next few build or so, we will move this section out into a new xml file.

And we will add the option of loading not only that default xml file but also player's only crew manifest.

**Comment by shirishag75** [comment]
looking forward to it.

**Comment by shirishag75** [comment]
> Please delete the `/conf` directory, it's NO LONGER being used.
> 
> We have been using `/xml` directory in the last 20 builds.

done.  Looking forward to know how to fix/have my own crew in console mode :)

**Comment by mokun** [comment]
@shirishag75 , 

Have you tried making your own crew in `crew.xml` yet ? 

We'll progress toward making the crew *transportable* between different simulation sessions.

**Comment by mokun** [comment]
Just corrected another issue with loading the *alpha crew* as listed in `crew.xml` in this [commit](https://github.com/mars-sim/mars-sim/commit/d0ce26263c7dcea6bc9186ca32414bb11fc7b1ee)

We also added the ability to send each crewman to a particular settlement destination, rather than mandating all of them to send to only one destination.

Will try to add the capability of saving the changes made to the alpha crew. 

Since crew.xml should be designated as **READ ONLY**, may be we should create a different json file just to store the changes.

**Comment by mokun** [comment]
@shirishag75 ,

We are improving the crew editor. On my way to add the ability to reload the default profiles to overwrite changes. Will add the ability to save it to crew.xml in near future so that you may tailor a dedicated crew for your simulation.

**Comment by mokun** [comment]
@shirishag75 ,

After the last commit, we are finally able to save the crew members that a player creates and store it as `beta_crew.xml`.

Note that for now, we standardize it to a crew of 5.

**Comment by mokun** [comment]
With this [commit](https://github.com/mars-sim/mars-sim/commit/4984f3e1b3d9553047269486db653a1e1e65f984), it will now compare the MD5 hash on each xml files in your home directory to see if it matches the MD5 hash of its counterpart inside the jar file.
