### ISSUE TITLE
Removing/canceling the command mode takes down the whole simulation. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#208]
whenever we start the simulation, we have the terminal window and the Command Mode or GUI mode window. Removing the command mode stops the terminal window and shuts down the simulation. This should not happen. At times I just want the terminal window and not the command mode window. There doesn't seem to be a way to divorce the two.

**Comment by mokun** [comment]
> Removing the command mode stops the terminal window and shuts down the simulation. 

There has to be two separate terminal windows by design.

Say you enter `java -jar xxx.jar` in a terminal window (T1) to start mars-sim.

Then, at the start of this sim, a new terminal (T2) pops up asking users to choose either the `command mode` or the `sandbox mode`.  

This `beryl` console/terminal has a running loop that query for user's input throughout the simulation. It functions also as a chat box.

T1 can print logs only. It dumps you information one-way.

T2 can read your input. So it's an interactive console.

> At times I just want the terminal window and not the command mode window. There doesn't seem to be a way to divorce the two.

Can you explain more ?

**Comment by shirishag75** [comment]
I was able to do what I want with using the headless version. I guess we just have to wait for the command mode to be completed to understand what is happening. I am also curious to know if the commander and the crew will have skillsets or something but that's for another day, I guess.

**Comment by mokun** [comment]
Yes each settler has various level of [skills](https://github.com/mars-sim/mars-sim/wiki/Skills)

**Comment by mokun** [comment]
It should be very easy to exit the beryl console now. Issue closed
