### ISSUE TITLE
Even with increased memory, I get no benefits in mars-sim-headless 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#214]
Hi all, 

I was expecting the java swing window to open faster in the headless version as I bought some additional memory but didn't see any change. 

```
$ sudo inxi -m
[sudo] password for shirish: 
Memory:    RAM: total: 23.41 GiB used: 2.80 GiB (12.0%) 
           Array-1: capacity: 64 GiB slots: 4 EC: None 
           Device-1: ChannelA-DIMM1 size: No Module Installed 
           Device-2: ChannelA-DIMM2 size: 16 GiB speed: 2400 MT/s 
           Device-3: ChannelB-DIMM1 size: No Module Installed 
           Device-4: ChannelB-DIMM2 size: 8 GiB speed: 2400 MT/s
```

I upgraded from 8 GB to 24 GB in one instance but didn't see an iota of dfiference in response time or anything else for that matter.

**Comment by mokun** [comment]
True. The thing is that currently, mars-sim doesn't make use of that much heap or stack memory. It probably uses less than 512MB and at most 1GB. 

See http://net-informations.com/java/cjava/memory.htm

**Comment by mokun** [comment]
> I was expecting the java swing window to open faster in the headless version as I bought some additional memory but didn't see any change.

btw, the headless Edition of mars-sim uses very minimal swing element such as drawing the black background console and one pull-down menu option and the top-left corner icon. That's pretty much it. It requires very little memory footprint on your machine.

But if you run the Swing Edition of mars-sim, it's another story. 

If you open the `Navigator Tool`, the machine will need to render the mini-`Mars Globe` and the `Surface/Topo Map` and both will be taxing. Same thing happens when you open the `Settlement Map`.

When we transition these map projection class to JavaFX, we'll refactor our codebase and use the latest rendering technique available.
