### ISSUE TITLE
people seem to be dying with low oxygen levels in their EVA suits, getting stuck and unable to exit some tasks

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#245]
Usually, when we think of astronauts, we usually think of them as intelligent people.But there seems to be an issue as even in early days, it seems people are dying left and right. In such a scenario where the commander doesn't make any decision (in headless edition) I dunno what would we be accomplishing. The first achievement by settlers should be oxygen, food, water, shelter and then move on to higher goals. Losing people would be bad for morale and also make the proposition far less appealing and expensive for people on Earth to appreciate being done by people on Mars. 

We don't want a zero-sum game at the end of the day . 

Also is there a way to get some more info. on what science is being done at each setlement to know what is being worked on or what kind of scientific studies are there to be studied ? Perhaps one is more beneficial than the other.

**Comment by mokun** [comment]
> The first achievement by settlers should be oxygen, food, water, shelter and then move on to higher goals.

Yes it's true.

>  it seems people are dying left and right. 

Can I see the stack trace or screen print of the situation you came across ? It will help debug what you have seen.

Accidents can strike at any moment in the simulation. But I agree we'll need to pin down any issues and make it reasonable. 

In mars-sim, we create the concept of *Malfunction* for modeling the breakdown of a system or sub-system.

If a malfunction is being reported, repairs are set to work so that this malfunction will result in minimal disruption. 

If an EVA Suit malfunctions, it can be life-threatening.

**Comment by shirishag75** [comment]
sharing mars_sim.log
[mars_simu_0.log](https://github.com/mars-sim/mars-sim/files/3966335/mars_simu_0.log)

that should give you all the info. you should need.

**Comment by mokun** [comment]
hmm. I can't think of any reasons as to why people from ALL SETTLEMENTS are dying one by one due to lack of oxygen. 

If An `Atmospheric Processor` has malfunction, it could reduce the oxygen supply for ONE settlement.
But it's not statistically possible for ALL `Atmospheric Processor` from ALL settlements to have malfunctions at the same time...

> 00-Adir-04:358.907 (Warning) TaskManager : Shawn Stewart - Sleeping's probability is at all time high : 144102.2.

Also, the probability for the Sleep meta task is super high. It's very suspicious of all kinds of system-wide bugs.

**Comment by mokun** [comment]
> Also, the probability for the Sleep meta task is super high which is very suspicious of some kinds of system-wide bugs.

Fixing this now. Seems like this is due to getting stuck at EatDrink task and not being able to exit.

**Comment by mokun** [comment]
This issue is overcome by other issues, a majority of which seem to have been resolved lately. Close this now.
