### ISSUE TITLE
having a form to populate crew.xml; add beta_crew.xml

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#251]
It would be nice if instead of having to write xml by hand it might be good to have a form which helps in completing crew.xml. This is a feature request, maybe something you can look at in few days. For e.g. I would be happy with a form which says something like - 

a. Which country ?
b. Number of people in crewl.xml (number )
c. Number of people of each gender (male, female, even transgender perhaps ) ?
d. Any children ?

While I haven't seen any children in the game yet I'm sure they will be sooner rather than later in the game.

**Comment by mokun** [comment]
That's why the `Crew Editor` has been created for giving you a graphical interface to change the attributes of each member of the Alpha Crew.

Since it's an on-going effort of giving players the ability to customize crew members, as of now, players will need the Swing Edition (NOT Console Edition) use the `Crew Editor` 

It is accessible via the `Site Editor` by Clicking the `Edit Crew` button.

![image](https://user-images.githubusercontent.com/1168584/71113009-8f7c3080-2181-11ea-9778-cd0e8a1dccbf.png)

**Comment by shirishag75** [comment]
I am looking for a solution which is slightly more automated for the console edition. It just asks me a bunch of questions and then prepares/makes a crew based on my choices. That would make it whole lot easier.

**Comment by mokun** [comment]
Just corrected another issue with loading the alpha crew listed in crew.xml in this [commit](https://github.com/mars-sim/mars-sim/commit/d0ce26263c7dcea6bc9186ca32414bb11fc7b1ee)

Will start working on the console alternative of the `Crew Editor` that aims to load and edit the alpha crew manifest.

**Comment by mokun** [comment]
@shirishag75 ,

See https://github.com/mars-sim/mars-sim/issues/207.

Adding the missing features to the crew editor as we speak.

**Comment by mokun** [comment]
@shirishag75 ,

This thread is similar to #207.

Close it if you're done the issue.
