### ISSUE TITLE
saving and loading unique.sim, heap memory needed for saving a sim

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#253]
Just like we have saving for unique saving sims, is there a way to tell the game to load unique named *.sim . For e.g. 

```
~/.mars-sim/saved$ ls
commander-is-in.sim  commander.txt  Mars.json  ui_settings.dtd  ui_settings.xml
```
I am also not sure when it saves game again after half an hour or whatever the savegame interval is, whether it would save to commander-is-in.sim game or something else.  Also at times, I got this  not sure why 

```
00-Adir-01:010.757 (Config) Simulation : Saving the simulation as /home/shirish/.mars-sim/saved/commander-is-in.sim..
00-Adir-01:010.757 (Config) Simulation : heapSize: 4.12 GB    heapMaxSize: 5.84 GB    heapFreeSize: 1.92 MB
00-Adir-01:010.757 (Config) Simulation : Not enough free memory in heap space. Wait for 3 seconds and retry...
```

**Comment by mokun** [comment]
> heapFreeSize: 1.92 MB

We need about ~110 MB RAM for LZMA2 encoder and decoder to work.

At that moment, there's only 1.92 MB RAM set aside as free heap space.

So, I program it to respond with that message. 

In `Simulation` class, you'll see
```
	/** The mininum size of heap space in bytes */
	public final static int MIN_HEAP_SPACE = 128*1024*1024;

```

After 3 seconds, the heapFreeSize could free up some more. If it's more than 128MB, it will serialize all the data successfully. 

It will attempt to check on the heapFreeSize at most 7 times if not successful.

I sort of laid that out in https://github.com/mars-sim/mars-sim/issues/248 what and why originally.
Since then, I've refined it a little bit.

**Comment by mokun** [comment]
> ust like we have saving for unique saving sims, is there a way to tell the game to load unique named *.sim . 

Yes, I just modify `MarsProjectHeadless` class to act like `MarsProject` class so that when you choose "2. Load from a saved sim", a JFileChooser will pop up and let you select whatever sim file you have in mind to load.

![image](https://user-images.githubusercontent.com/1168584/71050238-834c9080-20f9-11ea-8acc-66571f337e65.png)

Will commit soon

**Comment by mokun** [comment]
@shirishag75 ,

To load a sim called `123.sim`, just type in 

'>java -jar 3.1.1_swing_java14.jar load 123.sim'

**Comment by mokun** [comment]
Closing this.
