### ISSUE TITLE
which base inventory is being talked about ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#254]
See the following - 

```
00-Adir-01:213.934 (Info) DigLocalRegolith : [New Pompeii] shirish agarwal collected 50.0 kg regolith outside at 39.31° S
 7.00° W
00-Adir-01:220.392 (Severe) Inventory : Insufficient stored amount to retrieve regolith. Storage Amount : 0.0 kg. Attempt
ed Amount : 50.0 kg
00-Adir-01:223.532 (Severe) Inventory : Insufficient stored amount to retrieve regolith. Storage Amount : 0.0 kg. Attempt
ed Amount : 50.0 kg
```

From this it isn't possible to know which base's inventory are we  talking here. New Pompeii or some other base. 

Sharing the log so it makes more sense. 

[mars_simu_0.log](https://github.com/mars-sim/mars-sim/files/3976073/mars_simu_0.log)

**Comment by mokun** [comment]
After the last build, the log will provide the ownership info from now on.

The real issue lies on how the `Inventory` class has been setup in response to being asked to retrieve something.

There is a difference between retrieving something directly from a person vs. retrieving something from a bag (that holds the regolith) that's a property of a person.

**Comment by shirishag75** [comment]
share with me a log statement so I know the difference please.
