### ISSUE TITLE
Location logic spread around the various Unit class

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#296]
**Describe the bug/issue**
The LocationTag & LocationStatusType property logic are spread amongst the various Unit class. Eahc Unit subclass has to know about each other type of Unit subclass. The LocationStateType  is initialised in teh Unit constructor using instanceof; this means the Abstract super class knows about all the sub-implementation which is increasing the cohersion.

**Proposal **
All logic to identify location should reside in the LocationTag class. The location status type can be resolved in a generic manner by using the UnitType of the Unit and it's immediate parent;  for each combination the appropriate LocationstateType can be predefined in a lookup. 
The Unit class should provide the getCoordinates method but by default will delegate to the immediate Container. Only the Settlement & Vehicle subclasses can override the method to provide a physical location on the surface.

**Comment by mokun** [comment]
> LocationTag & LocationStatusType property

See [past discussions](https://github.com/mars-sim/mars-sim/issues/134)

We created `LocationTag` for giving a general location (thus `LocationStateType`) of an unit since we have wanted to reduce the cpu utilization of the lookup.

May we have used a bad architecture or approach. 

We would look at the previous `LocationStateType` to predict  the new `LocationStateType` that the person is transitioning into.

In doing so, we have to do a lot of branching conditions (if - else), which is a nightmare.

Yes. If you can find a better and also more efficient way, let's get rid of ugly methods such as `updatePersonRobotState()`, `updateEquipmentState()`, `updateVehicleState()`, etc. inside `Unit`.

**Comment by bevans2000** [comment]
This issue has been addressed in numerous other resolved issue. This is now too generic.
