### ISSUE TITLE
No documentation about how to clone repo and package the Debian build

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#3]
There is no documentation either in the git wiki or in sourceforge.net as to how it is being packaged into a .deb package. There should be some notes to get new people who might be interested in compiling and packaging it into distributions (later).

**Comment by mokun** [comment]
Currently, we are using a Maven's plug-in to automatically test and package all compiled java class into the .deb package as well as the other two .jar packages.

Before running maven, I'm supposed to update the content insides those .gz files manually (but Scott may have done it differently via some other means.)

So the whole thing is sort of semi-automatic. 

I'll try to capture what I did in wiki in near future.

**Comment by mokun** [comment]
When it comes to packaging or creating the .deb file, we use the following maven command to create both the .jar and .deb files in one shot : 

> mvn clean package install

Note that once you download all the dependent jars from maven, you don't have to do it again (unless we change the setting of the maven plug-ins, which is another story). 

So you don't need to "clone the repo" every time you run maven--if I understand what you mean by "how to clone repo"

**Comment by mokun** [comment]
btw, on a side note, recently I made a change in this (commit)[https://github.com/mars-sim/mars-sim/commit/5d27a02f09fc2332ec29d7a9543a0954aaa43873].

Since then, all the dependent jars on each module (mars-sim-core, mars-sim-ui, mars-sim-map, mars-sim-main, etc.) are now saved in the /dependency folder.

Before, all *.jar are stored in a local repository folder in a centralized manner. 

In Windows OS, it's at 

> C:\Users\[Your user name]\.m2\repository
