### ISSUE TITLE
Bug with lat/lon when adding settlements

### ISSUE THREAD

**Issue by Mocha2007** [mars-sim/mars-sim#33]
When you add new settlements, there are two spaces between the number and the N/S/E/W in the latitude/longitude which must be manually corrected before starting a game

**Comment by mokun** [comment]
Hi Mocha2007, you are right! I just happened to have addressed with the following two commits lately :

See
[r3876](https://github.com/mars-sim/mars-sim/commit/c0288da9c5b35b43b1befe87573c9588e27bb008)

[r3879](https://github.com/mars-sim/mars-sim/commit/dd78a2542e6bcd25a8f48f2a76c9a4ee0ade4bae)

For now, I make it a requirement to have one whitespace in between the decimal number (X.X) and the N/S/E/W. I should have spelled that out even more clearly what the required input format is.

It will be included in 3.1.0-p6.

Don't hesitate to report any bugs or provide any feedbacks.

Thanks for being observant !

**Comment by mokun** [comment]
I just rewrote the red error msg for flagging any bad latitude/longitude : 

e.g.
> The latitude must be in the format of #.#_D. e.g. 3.1 N or 80.9 S (Note: #.# is a number round to 1 decimal place, followed by one whitespace. D is the direction N or S)

To simplify the input, I also added a brand new method called removeUnQualifiedChar() in TableViewCombo to look for and automatically get rid of any invalid input characters in these four text fields (Bot, Settler, Latitude and Longitude) in the config editor.

See [r3891](https://github.com/mars-sim/mars-sim/commit/64787caebc9ecc883fc0bfadf8f2289119db7cba)

**Comment by mokun** [comment]
It was brought up to me lately that comma is sometimes used by languages other than English to denote the decimal mark, namely ",". see https://en.wikipedia.org/wiki/Decimal_mark

While the dot or the period is used in English as the decimal mark, the comma mark is typically used in English as the separation mark for a thousand. e.g. "13250 W" is the same as "13,250.00 W".

But since latitude will only have value between 90 and 0 (N or S) and longitude will not have value higher than 180 (E or W), the use of comma in latitude and longitude in the Config Editor should be easy.

In that case, I'll modify the validation code to accept the comma as well. 

e.g. for latitude, input "3,1 N" is no different from "3.1 N" and both will be accepted.
In case of longitude, input "179.3 S" is the same as "179,3 S" and both are legit.

**Comment by larsnaesbye** [comment]
Yes, in e.g. Denmark the roles of comma and point are reversed. Comma is used as decimal mark, while point is a thousands separator.

**Comment by mokun** [comment]
We've taken care of this issue for now. As we put in more effort in internationalization, we could redo the UI to display the decimal mark in accordance with whatever language the users prefer
