### ISSUE TITLE
Limiting the size of the heap space

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#335]
Q: What can be done to reduce the use of the heap space size ? 

When the heap size get near 1.5GB, the autosave feature can crash the simulation.

Below is one scenario of running out of heap space in the stack trace

```
00-Adir-03:317.931 (Config) Simulation : Saving the simulation as default.sim.
00-Adir-03:317.931 (Config) Simulation : heapSize: 1.50 GB    heapMaxSize: 1.50 GB    heapFreeSize: 203.67 MB
Exception in thread "masterclock-0" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.ObjectOutputStream$HandleTable.growEntries(ObjectOutputStream.java:2365)
	at java.base/java.io.ObjectOutputStream$HandleTable.assign(ObjectOutputStream.java:2294)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1437)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1387)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.base/java.io.ObjectOutputStream$PutFieldImpl.writeFields(ObjectOutputStream.java:1723)
	at java.base/java.io.ObjectOutputStream.writeFields(ObjectOutputStream.java:487)
	at java.base/java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1417)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1196)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.writeObject(ConcurrentLinkedQueue.java:824)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1196)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
```

Note that I increase the time ratio to 512x.

The memory bar on the bottom right of the main window shows it was 1.29GB when I clicked on the save button and expect the sim to be saved.

However, it went frozen in the Eclipse IDE because it had an out of memory exception. It didn't get saved.

**Comment by bevans2000** [comment]
The sim should have a mainly consist size. It will create new Task & Mission objects but that is all. This would impact the TaskSchedule class as well. Do we keep references to old completed Missions?
One potential source of growth is the map in LogConsolidated (& the replacement SimLogger). This may be growing continuously and that is a place to investigate. There is no purging or ageing out process of the entries so I expect it will be big.

**Comment by bevans2000** [comment]
I ran the simulation for a few minutes and the memory analyser showed these initial "issues":
- Many of the Config objects are still retaining the JDom Document in memory. We should rework these and load the contents into an optimal representation. I have done this for the MalfunctionConfig & BuildingConfig already.
- The LogConsolidated is never releasing cached messages; they are retained forever. The SimLogger replacement has a more optional approach by purging the history and being more selective in which messages are cached. We should continue to replace the old with the new plus it simplifies the calling code as well because decribing hte location context is pushed into the base class. This gives us a consistent approach and less code.
- The mapdata package classes consume the 4% of the total memory. There is a large Int array that seems toe be shared by all the classes. Instead of loading the whole of the Mars Surface could we look to cache regions and load on demand? Might be a difficult change but worth considering.
- Swing UI Global Display class uses a lot of memory. I don't know this class so can't comment on it.
- There is something wrong in the TaskMeta framework because I found 863 copies of the ReadMeta class for example. There should only be a single one as it is constructed in the MetaTaskUtil. I suspect the problem is the over use of CopyOnWriteArray and it not being thread safe being it creates new objects. I will look into this.

Needs further analysis.

**Comment by mokun** [comment]
Thanks for investigating this.

Yes I suppose when we move to Java 17, whatever garbage collector it will bundle with will also be more light-weight and probably have more options to play around.

Still it's a great thing to optimize our codebase on our end.

> * Many of the Config objects are still retaining the JDom Document in memory. We should rework these and load the contents into an optimal representation. I have done this for the MalfunctionConfig & BuildingConfig already.

Sure. I'll rework some Config class today.

**Comment by bevans2000** [comment]
The rework of Config can be quite an effort but it is better because the internal representation has a smaller memory footprint and us  ore optimal. 
A different garbage collector won't help because it will not release active objects. We need to reduce the memory footprint and reduce the memory increase over time.

**Comment by mokun** [comment]
> * The mapdata package classes consume the 4% of the total memory. There is a large Int array that seems toe be shared by all the classes. Instead of loading the whole of the Mars Surface could we look to cache regions and load on demand? Might be a difficult change but worth considering.

Absolutely ! the Int array is big. I have wanted to double the resolution of the map but that would mean x4 the Int array.

If we can find a way to incorporate some Java utility for loading map tiles by region, it would be great.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

Still our current map tools are inadequate as it doesn't allow some limited form of zooming in and out of an area on Mars. 

Even the zooming in/out of a settlement on the Settlement Window is a bit fictitious since it only enlarges/shrinks the svg building icons but not the surrounding Martian soil landscape. 

The background tile has rendering artifacts if you zoom in and out fast.

Q2 : What route of planning should we take to add some semi-permanent topological features or temporary man-made structures to the surrounding of a settlement (or outside a settlement) in near future ? 

Say, we want to include man-made structures such as weather stations, water drilling rigs or regolith/mineral excavation pits, etc.

**Comment by mokun** [comment]
Let's move our discussions of the map tool to this new [tracker](https://github.com/mars-sim/mars-sim/issues/336).

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

> The rework of Config can be quite an effort but it is better because the internal representation has a smaller memory footprint and us ore optimal.

Besides removing any JDOM objects, I'm also add the keyword transient or static to some data objects in those config file.

Since we are reloading each config file when loading from a saved sim, do we still need to serialize those lists and maps ? 

Is there a way to not mess up the object references while at the same time not needing to serialize them ?  

I'm also trying to see if static is better than transient in terms of memory access/usage.  
See [1](https://www.educba.com/types-of-memory-in-java/) and [2](https://stackoverflow.com/questions/3849634/static-allocation-in-java-heap-stack-and-permanent-generation).

**Comment by bevans2000** [comment]
Well when I did BuildingConfig the internally created object are not referenced by the Serialized Building; they are only use use to construct new Buildings.
For MalfunctionConfig; the MalfunctionMeta is serializable so when a Malfunction is serialized it's definition is also serialized. When reloaded if the definition of Malfunctions change it should not affect the Malfunctions already active.
The key is to look at the methods in the config classes that need to use the Document once the initialisation has completed. They need to be looked at and addressed.

**Comment by bevans2000** [comment]
I've done some analysis on the memory growth and found these problems:
- Weather, this class is recording the historical weather nearly every pulse which means after 10 minutes running it already created 6884 entries. Each is not that big but the total soon mounts up. I will fix this as it seems to be the old approach to the MarsClock.
- There are a large (and increasing ?) number of Coordinate objects. This probably due to Vehicle & Equipment location being tracked.
- Temporary created MetaTask objects to lookup Person preferences get persisted in the preference map because there is no valid equals on the MetaTask classes. This can be fixed by using name instead internally within Preference.

I plan to rework the TaskMeta approach as part of #297 such that it becomes data driven instead of the various MetaTask instances being explicitly referenced in numerous locations. Essentially making it easier to add new Tasks with a more plug and play strategy.

**Comment by mokun** [comment]
In case of the Complaint class, it should be a "data" class and doesn't have any mutable members.

Should we switch to using ComplaintType, which is the enum version of a Complaint object, in light of all those potential serialization issues?

See https://stackoverflow.com/questions/18361190/serialization-of-enum-fields-in-java.

Below is from PhysicalCondition class, 
```
	/** List of medications affecting the person. */
	private List<Medication> medicationList;
	/** Injury/Illness effecting person. */
	private Map<Complaint, HealthProblem> problems;
	/** Record of Illness frequency. */
	private Map<ComplaintType, Integer> healthLog;
	/** Record of illness start time. */
	private Map<ComplaintType, List<String>> healthHistory;
```
I'll rework `Map<Complaint, HealthProblem> problems` to `Map<ComplaintType, HealthProblem> problems`.

Also Within `HealthProblem`, I'll rework it to contain `ComplaintType`, instead of `Complaint`.

It seems that when we use methods to compare ComplaintType, it will avoid having the serialization issue we have been, especially after loading from a saved sim.

**Comment by mokun** [comment]
Closed.
