### ISSUE TITLE
Everyone suffocates on save load

### ISSUE THREAD

**Issue by Mocha2007** [mars-sim/mars-sim#34]
I even created a new game, immediately saved it, and loaded it. They all die of suffocation. Not sure why.

**Comment by mokun** [comment]
True. I'm still trying to figure out why they suffocate. 

We use Java's built-in methods for serializing (saving) and deserializing (loading) objects. The serialization works but not deserialization. 

The problem centered on problems deserializing the Inventory instance for the Settlement class and the EVASuit class.

I'll try to dig deeper to see what went wrong.

As a temporary stop gap measure, I turned off the checking of oxygen/water in [r3889](https://github.com/mars-sim/mars-sim/commit/6cce0021dfa4cf89d6577babc51e2335c6f66059)

Perhaps things will get easier to debug in future after we move to saving and loading sim in JSON format.

**Comment by mokun** [comment]
The suffocation bug during loading has just been fixed in [r3898](https://github.com/mars-sim/mars-sim/commit/9e533191c8e00eceea7b5ff9b4a2c8b8d3e5b9f6). 

It appears the reasons are two folded as to why settlers are complaining about insufficient O2/H2O and getting suffocated :

1. Invalid initialization of some Amount Resource instance fields. Also, some should not be declared static. I traced the bug all the way back to r3810, in which some AmountResource instances was not re-initialized correctly by Java de-serialization because they were declared static. 

2. NullPointerException due to assessing empty Maps that are set up as Amount Resource caches.
NullPointerException happens when trying to get values from some 'empty' amount resource cache after loading the saved sim in Inventory class.

Note: this suffocation bug has been plaguing mars-sim v3.1.0-p4 and v3.1.0-p5 as well. The fix will be incorporated into v3.1.0-p6.

**Comment by mokun** [comment]
Done.

**Comment by mokun** [comment]
Turns out this bug has not been fixed completely as of r3929. 

Numerous NullPointerException in Inventory class was indeed resolved in r3898.

But none of the amount resources actually got carried over to the Inventory class upon loading a saved sim.

**Comment by mokun** [comment]
This issue has been resolved. check out v3.1.0-p7
