### ISSUE TITLE
Validating the latitude and longitude of a settlement coordinate

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#354]
**Describe the bug**
- The Site Editor (aka Simulation Config Editor) does not correctly validating the latitude and longitude of a settlement to 2 decimal places.
- The `New Arriving Settlement` choice when creating a brand new transport mission in the `Resupply Tool` would always lead to a failed the latitude and longitude coordinate test and thus cannot create a new settlement.

**Expected behavior**
- The Site Editor should correctly validate the latitude and longitude of a settlement. No settlement should occupy the same x/y coordinate (up to the 2 decimal places.
- The `New Arriving Settlement` should be a viable option when creating a new transport mission in the `Resupply Tool`. It should validate the coordinate input.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/120711399-2f13a880-c474-11eb-8e6b-b0571c33eee4.png)

**Desktop**
 - Build 5772

**Comment by mokun** [comment]
This is in response to this discussion [post](https://github.com/mars-sim/mars-sim/discussions/304#discussioncomment-600095).

**Comment by mokun** [comment]
@bevans2000 ,

When I create a *new Arriving Settlement* using the `Resupply Tool`, the new settlement is created but it shows exceptions in the threads and the new settlers, new bots, new vehicles never get updated.

Can you find out what goes wrong ?

![image](https://user-images.githubusercontent.com/1168584/120723517-c2ee7000-c486-11eb-8eaf-d55524aea3d3.png)

**Comment by bevans2000** [comment]
Sure I'll have a look

**Comment by bevans2000** [comment]
I can sort this I think. Basically there are 2 issues:

1. The new Settlement is registered with the UnitManager before it is initialised
2. UI reacts to UNIT Event and generates a null pointer because the Unit is not fully populated.

The root cause is the Settlement (& Units in general) register themselves with the UnitManager during their constructor. This is a bad pattern; in theory you should never use `this` as an argument in a constructor. The creator of the Unit should register the new Unit once it has completed. 
I will look into it tonight; there maybe too much dependence on the UnitManager.getById methods when dependent object should already know their parent without the need for a lookup. Should also improve performance to remove the lookups.

**Comment by bevans2000** [comment]
Committed some changes to resolved this problem. Uncovered an issue where Units are registering themselves with the UnitManager before they are fully initialised.

**Comment by bevans2000** [comment]
Can we close this now?

**Comment by mokun** [comment]
> The creator of the Unit should register the new Unit once it has completed.

oic.

**Comment by mokun** [comment]
> Can we close this now?

Yes. Closing this.
