### ISSUE TITLE
MissionTableModel shows invisible rows

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#374]
**Describe the bug**
- Sometimes right after a new mission is created, it is NOT shown in the mission tab of the Monitor Tool. Rather, it is listed as an "invisible" row. See picture below.
- The Mission Tool did has this mission

**Expected behavior**
- Any on-going mission is supposed to be shown. Any cancelled missions are supposed to be deleted. There is no in-between.
- once the List missionCache is created in MissionTableModel, it will NOT need to be replaced. But it can have new elements by calling addMission() or lose elements by calling removeMission(). 

**Desktop (please complete the following information):**
 - build r5947
 
**Screenshots**

There is a total of 10 on-going missions generated for this simulation session. However, only 2 missions are visible. The rest of the 8 missions are invisible.
![image](https://user-images.githubusercontent.com/1168584/125743085-9423e860-ef25-4de1-9b4f-abdc90fee56b.png)

**Comment by bevans2000** [comment]
Certianly looks odd.  I'll run a longer simulation tonight

**Comment by mokun** [comment]
Looks like the MissionTableModel can't properly add a mission and can't update those new missions.

**Comment by bevans2000** [comment]
The problem is in the TableSorter class. It only has the index for 1 row but there are multiple rows in the source model. However there is an unreported Exception that is masking the problem.
Not sure what the fix is yet.
```
    public Object getValueAt(int aRow, int aColumn) {
    	try {
    		return sourceModel.getValueAt(indexes[aRow], aColumn);
    	}
    	catch (Exception e) {
    		return null;
    	}
```

**Comment by mokun** [comment]
Hmm. I thought it may have  to do with the mission listener not working. It's good you found something

**Comment by bevans2000** [comment]
I've found the problem. Should have a commit soon. Just running some tests

**Comment by mokun** [comment]
> I've found the problem. Should have a commit soon. Just running some tests

oic. Thanks!

**Comment by bevans2000** [comment]
Should be fixed with the latest commit

**Comment by mokun** [comment]
Interestingly, getCountString() isn't working. 

```
	/**
	 * Gets the model count string.
	 */
	public String getCountString() {
		return " " + Msg.getString("MissionTableModel.numberOfMissions", //$NON-NLS-2$
//			Integer.toString(missionCache.size())
				missionCache.size());
	}

```

![image](https://user-images.githubusercontent.com/1168584/126413687-81dda5d4-6d59-406f-88bb-753d33038af8.png)

Both MonitorTab and TableSorter has getCountString() and supposedly they call MissionTableModel's getCountString() to get the latest update of the # of missions.

But somehow, all it gets is a stale value.

**Comment by mokun** [comment]
Also, it seems to recycle the ID value. The id of Delivery #1 should be the greatest number but it's not.

![image](https://user-images.githubusercontent.com/1168584/126440967-d6740d7e-8d4c-4f86-9cfd-0eb569dd9840.png)

Q1 : Should we be keep the id as the number of missions generated so far (though not all of them are executable) ?

Q2: What's the best way to tell the two Mineral Exploration missions apart from each other ?

**Comment by bevans2000** [comment]
Are you sure that the 1st column is  not just the row id?

**Comment by mokun** [comment]
> Are you sure that the 1st column is not just the row id?

The 1st column is created by using the RowNumberTable class in TableTab.

https://github.com/mars-sim/mars-sim/blob/59886bdef125a836f9e823f588564e7865e0b0d1/mars-sim-ui/src/main/java/org/mars_sim/msp/ui/swing/tool/monitor/TableTab.java#L224-L225

The weird part is that Delivery #1 is generated on 00-Adir-04. So it's supposed to be the latest one. But it should have #1. 

To add to the intricacy of what we are dealing with, we know MissionManager will delete any unsuccessful missions from the list of ongoing missions. 

Q1 : do we still want a global numeric mission ID for all settlement ? 

Q2: should we expect some skip in number to show up in Mission Tool ?  

Say *Mineral Exploration#1* does not get approved. 

Next, *Regolith Mission#2* get approved. 

So we won't see *Mineral Exploration#1* but will see *Regolith Mission#2* showing up in the Mission Tool.

**Comment by mokun** [comment]
And we are to figure how to fix 
- the traveled distance
- the remaining distance
- the proposed distance

![image](https://user-images.githubusercontent.com/1168584/126742617-c8141a2a-a270-409a-8fc4-3e4c8e93f0a0.png)

Note that for Trading and Delivery mission, we need to find a way to account for the return trip. 

It seems currently those numbers aren't right for these two missions. 

At the same time, we want to save a record of these 3 distances. 

When the settlers returned and these distances will remain and NOT be set to zero - currently something's not done properly.

**Comment by bevans2000** [comment]
> Q1 : do we still want a global numeric mission ID for all settlement ?
The Missionmanager is a global entity with a single list BUT in reality the Missions are controlled by the initiating Settlement so in theory it should be an instance per Settlement and then a read-only "Facade" class over the total to give a global view. This obviously helps with Thread safe  because we know entities within a single Settlement get updated by the same Thread.
One idea I was thinking about generally was having a short name (3 characters) for each Settlement then this short name plus a Settlement id would give a unique name. Personally I would also have a shortened name for Missions types as well. So in this world Mission would be named "SCH-MEX-01" for a Mining Exploration out of Schiaparelli Point.

> Q2: should we expect some skip in number to show up in Mission Tool ?
Yes because should get started and then closed if not approved

**Comment by bevans2000** [comment]
@mokun  I found your problems with the Mission Monitor.
1. The currentLocation for a mission is based on the Member so for Delivery it always returns the starting Settlement. I have override the method in `VehicleMission` to directly use the vehicle location.
2. Stalled mission planning was due to a change you made for the Delivery Mission in the `Mind.lookForATask`. The condition of checking for Delivery excluded all other Mission types. Using the Class in the logic is causing problems; we need to refactor to have a new method `boolean Mission.stillMember(Worker)` which can handle the logic of what the rules are for Member to remain on a mission. 

However both of these uncovered further problems:
1. In the `ResourceUtil.mapInstance` method where the REGOLITH_TYPES was initialised out of order and hence containing '0's. This got introduced in ed1762791e21f13b91596372188e10844d714166. All seems to be working fine now.
2. Now missions are based on Vehicle location; when a Vehicle region with no Sun the mission stops, again `Mind.lookForATask` which stops when in low sunlight. Now the question is why? Again this should be mission specific. However it seems the getSunLightRatio is always returns 0.1 for some locations. I can't understand why but temporarily I have commented out the sunlight check. Although the Missions still can stall due to the priority check.

Also I noticed the the `Coordinate` class is not immutable but it gets used as a key for Maps. This is a problem because the value of the key can change after it has been increased giving the wrong result in lookups. I will create a separate Issue for this.

**Comment by mokun** [comment]
> which stops when in low sunlight. Now the question is why? Again this should be mission specific. However it seems the getSunLightRatio is always returns 0.1 for some locations. I can't understand why but temporarily I have commented out the sunlight check

Here's the reason for doing `if ((sun <= 0.1) && !inDarkPolarRegion)`

Normally, in the near equator zone, sunlight can go from 0 to 1 throughout the day. 

Here, however, checking sun is needed for those settlement that are in the polar region (thus inDarkPolarRegion is true).

e.g. In the north pole, sunlight will be perpetually at ZERO for 3 months or so during winter time. Then sunlight will be perpetually at above zero throughout the day for 3 months or so during the summer time.

This is similar to, say, living in North Sweden where there's no sun in some winter days.

**Comment by bevans2000** [comment]
Ok so you might want to revisit what I did but I found that Zverda was always coming back as low. But it will still be better because Missions will advanced after these changes.

**Comment by mokun** [comment]
> Ok so you might want to revisit what I did but I found that Zverda was always coming back as low. But it will still be better because Missions will advanced after these changes.

hmmm. Zvezda is at 25.94 N and 76.37E only. Still fairly near the equator. 

![image](https://user-images.githubusercontent.com/1168584/127064747-16a58ca2-b17f-4a37-b61e-e08cdb73e13b.png)

So the sunlight shouldn't be at zero for the whole day or so.

**Comment by mokun** [comment]
So currently, 

getSunlightRatio() and getSurfaceSunlightRatio() are in SurfaceFeatures. They are doing the calculation differently from the each other.

```
	/**
	 * Calculate the solar irradiance ratio (between 0 and 1) at a particular location on Mars
	 * 
	 * @param location the coordinate location on Mars.
	 * @return (between 0 and 1)
	 */
	public double getSunlightRatio(Coordinates location) {
		  return Math.round(getSolarIrradiance(location) 
				  / MAX_SOLAR_IRRADIANCE * 100D)/100D;
	}
```

getSunlightRatio() relies on getSolarIrradiance() and is a time consuming process of deriving the sunlight leve.

getSurfaceSunlightRatio() is much simpler but not as accurate.

**Comment by bevans2000** [comment]
Ok. try changing it back in the Mind class to use surface solar ratio. All I can say is some Delivery missions appeared to get stuck once the drone entered a dark zone. I didn't want investigate further because I wasn't fixing that problem but it seemed at unexpected location for such a logic check. Surely such a check only matters to some Missions, for example an Emergency Mission you would keep going.

**Comment by mokun** [comment]
> All I can say is some Delivery missions appeared to get stuck once the drone entered a dark zone

Ok. I do notice some delivery missions stop midway. Now that you mentioned about sunlight,, I'm beginning to understand why it can't fly because it's possible that that person as the pilot may be sleeping and cannot call resumeMission(). 

So we need to have special logics to account for pilot/driver to continue operating the vehicle during the mission. 

If for whatever reason he can't operate the vehicle, he must get off the vehicle operator assignment and let someone else does it. He can't continue to occupy the vehicle operator role.

**Comment by bevans2000** [comment]
One problem I see if there is a double checking of fitness. In the Mind:lookForANewTask we check Person::isFit (true or false) but then in resumeMission we use the fitness rating to bias the mission selection. If a person is not fit then the bias will never get applied; hence 1 check masks the more granular one.
I think we shouldn't be checking for fitness at all but only use it in resumeMission to bias the random selection because the fitness check is specific for different mission types/phase combination. So for example, in a VehicleMission phase TRAVELLING anyone should be able to drive otherwise a Vehicle becomes stuck if all the crew are slightly unfit. In this situation the Vehicle stops moving and runs out of food and they all die. They should have been able to keep driving and return home once the lack of food was detected..
Another example is MineralExploration EXPLORE_SITE phase; in this combination, as it involves EVA, people should be fit but the TRAVELLING phase anyone can drive.
I think the Mission::canParticipate method is the place to push the logic to decide if a Person/Robot can do the work. Otherwise  the Mind class is going to become polluted with Mission logic.
Missions are like Task and we need to think of a plug-and-play design; to create new Mission types we shouldn't have to go into the core classes and change them.

**Comment by mokun** [comment]
> So for example, in a VehicleMission phase TRAVELLING anyone should be able to drive otherwise a Vehicle becomes stuck if all the crew are slightly unfit.

Okay. point taken. 

In the past, we have wanted to avoid some poor in physical health to go outside since one may get zero performance and stranded outside and died. 

Also, it won't make sense for a tired settler to be sent outside.

But being in a mission is different, the driver may get very tired and need to rest a lot in the vehicle after getting done driving and have no time going out exploring.

**Comment by mokun** [comment]
Let's continue the discussion on the fitness level on a different thread.

Closing this one now since the mission table model is fixed.
