### ISSUE TITLE
new speed panel is worse than old (IMHO)

### ISSUE THREAD

**Issue by Musickiller** [mars-sim/mars-sim#44]
Not a big issue, but I think that at some point it may still be important:
New speed panel does not allow to choose time ratio as well as old one. Which is not cool. Since a pause window is big and..
https://yadi.sk/i/fpBjotS23GR7Uy
..everywhere (not only on linux as I thought before), I thought to just make the simulation run at 1x realtime speen (which also feels cool - lil' ppl live their life in real time - a nice screensaver xD), but the new speed panel said I can make it as low as x32, but not any lower =(

If you disagree with me completely, you can dismiss this issue too - sorry for bothering with my (a bit too personal) wishes =D

**Comment by mokun** [comment]
> New speed panel does not allow to choose time ratio as well as old one...

As you might have noticed, I was aiming at fixing a few things with the old Time Tool since preview 2...

First, as you can still see in preview 3, the old Time Tool "centers" at the default time ratio of 500x, which is translated into "1 real sec equals 8m20s" in the simulation. 

However, if you ever move to the left of the slider and try to come back to the center again, it won't work. It would settle at "1 real sec equals 8m21.187s", not the near perfect 8m20s anymore.

So I found the Math responsible for computing the position of the slider and the corresponding time ratio has some serious flaw in it. The 500x center (by the way, in v3.07, it used to be 1000x) was arbitrarily chosen and the left side and right side of it was not divided up correctly. 



In v3.07.

For some strange reason, it also allows user to adjust the time ratio to go on reverse to 1/1000x. In that case, 1 real sec equals .001 sim sec.

If you

**Comment by mokun** [comment]
btw, after this [commit](https://github.com/mars-sim/mars-sim/commit/5ed7b4468a6ff902d80183ba9dd671d7e227cfad) , the range of the time ratio (from the highest to the lowest) are now determined by how many CPU/threads the machines has.

**Comment by Musickiller** [comment]
My problem with it is that the lowers time ration possible for now is x32. it's more or less OK, but why would you limit it? OK, may be I'm just not getting something - it's 01:08 here - I'll read it all again yesterday.

By the way, may be I'm mistaking here, but once it looked as if the ration reset itself to x64 for no obvious reason. That's why I've started to dislike the new system so much =D But I might have pressed some wrong button... If I ever see it happen again - I'll notify you.

**Comment by mokun** [comment]
> lowers time ration possible for now is x32

It's sort of a indirect design choice because there are good reasons and coding mechanics involved.

As of now, there are 77 tasks and 12 missions a settler can engage in but at a given moment the available tasks/mission are reduced by one's Job and Role and whether he is on or off duty.

In reality, what a human being may do is practically unlimited, or perhaps limited only by our own imagination :p 

In other words, the takeaway is that there aren't much going on at each second. So I thought it would be a good thing to speed up the passage of time and let users see changes happening faster.

On the other hand, the slider bar has discrete number of positions. 

As you can see below in MainScene class, 

a. I set the max to 8 times the initial time ratio. 

b. each increment is represented by 1/4 of the value of initial time ratio.

c. I set the minimum time ratio to 1/4 of the value of the default time ratio.

```
		initial_time_ratio = Simulation.instance().getMasterClock().getDefaultTimeRatio();

		//timeSlider.prefHeightProperty().bind(mapNodePane.heightProperty().multiply(.3d));
		timeSlider.setMin(0);//initial_ratio/16D);
		timeSlider.setMax(initial_time_ratio*8D);
		timeSlider.setValue(initial_time_ratio);
		timeSlider.setMajorTickUnit(initial_time_ratio*2D);
		//timeSlider.setMinorTickCount((int)(Math.round(initial_ratio/8D*100.0)/100.0));
		//timeSlider.setShowTickLabels(true);
		timeSlider.setShowTickMarks(true);
		timeSlider.setSnapToTicks(true);
		timeSlider.setBlockIncrement(initial_time_ratio/4D);


        timeSlider.valueProperty().addListener(new ChangeListener<Number>() {
            public void changed(ObservableValue<? extends Number> ov,
                Number old_val, Number new_val) {
            	if (old_val != new_val) {
	            	double sliderValue = new_val.doubleValue();
	            	double min_ratio = default_ratio/4D;

...

```

We could tweak the max value to 16x, change the increment to a different value, and change the minimum time ratio to 1/8 of the value of the default time ratio, etc..

It's harder to make it go down to exactly 1x to since it would distort how much each increment represents and it would create time ratio have decimal places (e.g. 40.25x) like in the old Time Tool that are prone to error. 

I'd rather have the whole number and is the multiple of 2 (e.g. 8, 16, 32, 64).

**Comment by mokun** [comment]
btw, in typical simulation games like the Sims, the speed control bar has 3 basic buttons only--the pause/play, faster and slower. It's offending to engineers as to what fast/slow means precisely but that's what most gamers prefer, something that's easy to comprehend :p This tells me you are one of those top 1% of people having more refined taste :)

**Comment by mokun** [comment]
Just refined the parameters in the time ratio slider. 
(1). at the start of sim, it's centered at the middle of the slider. 
(2). The min value is now always at 1.
(3). The max value is default time ratio * 16.

Let me know if you like this better !

```
		timeSlider.setMin(0); // need to be zero
		timeSlider.setMax(12);
		timeSlider.setValue(7);
		timeSlider.setMajorTickUnit(1);
		timeSlider.setMinorTickCount(1);
		timeSlider.setBlockIncrement(1)

        timeSlider.valueProperty().addListener(new ChangeListener<Number>() {
            public void changed(ObservableValue<? extends Number> ov,
                Number old_val, Number new_val) {
            	if (old_val != new_val) {
	            	double sliderValue = new_val.doubleValue();
	            	if (default_ratio == 64)
	            		newTimeRatio = Math.pow(2, (int)sliderValue - 1);
	            	else if (default_ratio == 128)
	            		newTimeRatio = Math.pow(2, (int)sliderValue);
	            	else if (default_ratio == 256)
	            		newTimeRatio = Math.pow(2, (int)sliderValue + 1);
	            	else if (default_ratio == 512)
	            		newTimeRatio = Math.pow(2, (int)sliderValue + 2);

			masterClock.setTimeRatio(newTimeRatio);

```

**Comment by mokun** [comment]
See [3906.7z](https://www.dropbox.com/s/kcq976mhmtpwu7s/3906.7z?dl=0l) on the improved the time ratio slider.

**Comment by Musickiller** [comment]
I think it didn't work =|

Maximum time rate (512): https://yadi.sk/i/WlRtodZI3GTNgp
Minimum time rate that is on the slider, but I have to hold my LMB pressed in order to maintain it: https://yadi.sk/i/8BdeYeir3GTNij (16): https://yadi.sk/i/8BdeYeir3GTNij
Actual minimum time rate (32): https://yadi.sk/i/905tSsoG3GTNtW

**Comment by mokun** [comment]
The pic shows you are running 3902.

One mistake I made in the past was, say, putting 3902.jar, 3903.jar. 3904.jar, etc., all in the same directory in Windows OS. When I click on 3904.jar, it would sometimes end up running 3902.jar instead. Why? because I ran 3902.jar last time and it still in the "cache" and 3902 and 3904 had the same internal version name.

**Comment by mokun** [comment]
Yes you can drag and drop pic file into GH. It has a limit of 1 MB

**Comment by mokun** [comment]
For some strange reason, there's a big gap between the LanderHab and each of the hallway. The LanderHab got shrunk down and did not touch the hallway. That didn't happen on preview 5. I'll look into it.

**Comment by Musickiller** [comment]
> The pic shows you are running 3902.
>
>One mistake I made in the past was, say, putting 3902.jar, 3903.jar. 3904.jar, etc., all in the same directory in Windows OS. When I click on 3904.jar, it would sometimes end up running 3902.jar instead. Why? because I ran 3902.jar last time and it still in the "cache" and 3902 and 3904 had the same internal version name.

Can you PLEASE change internal version name for each build? OR at least warn about those things every guy who does the testing. So now I know that it is possible that all the testing of new builds I have done was in vain - I was running 3902 all the time. Sucks. So. Much.

>Yes you can drag and drop pic file into GH. It has a limit of 1 MB

Or you can press PrtScr button and then Ctrl+V to paste your current screen. Avesome.

By the way, what OS do you have?

> For some strange reason, there's a big gap between the LanderHab and each of the hallway.

Yes, but I thought I should leave this problem for later - so that I would not be a representation of buggines and bad luck of your project in our eyes.. Kidding. I'm lazy.

**Comment by Musickiller** [comment]
Yes, as I have expected, it works. Without any changes to my system. But with LOTS of errors. Good news: I like the new speed bar and lack of large pause window very much.

[log.txt](https://github.com/mars-sim/mars-sim/files/880163/log.txt)

**Comment by Musickiller** [comment]
I think we can close this issue, the new bar is more or less what you have described as what you have aimed to achive, AND what I liked in old versions of MarsSim (I have opened this issue and I don't have issues with the new version = OK, I think =)))
We can continue talk about new errors in 38'th.

**Comment by larsnaesbye** [comment]
Closing it, then :-)
