### ISSUE TITLE
Concurrency problem when unloading at a trading settlement

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#484]
**Describe the bug**
When unloading a Vehicle at a remote Settlement for a Delivery/Trading Mission there is a chance that a Concurrency Exception can be raised. This is because a Mission Member from the starting location unloads the Vehicle at the remote Location. This means 2 Thread may be updating the inventory of a Settlement in parrallel.

**To Reproduce**
Run a Simulation with multiple Settlements and eventually a Concurrency Exception may get raised if there are many Delivery mission active.

**Expected behavior**
Only Persons that belong to a Settlement should be updating the Settlements inventory. This makes sure there can be no Thread safe issue since the Settlement's entity are always updated from the same Thread.

**Comment by bevans2000** [comment]
There is still a problem in the ```DeliveryUtil``` class when it is calculating good values; not as bad as the temp equipment problem. 
Sometime it calculates the good value for a selling settlement which is under the control of a different Thread but that Thread is doing an local Load/Unload task and hence the inventory changes. Also the TradeUtil & DeliveryUtil appear to be ~ 80% duplicate code. 
I think the way forward is for each Settlement to calculate an 'Inventory Audit' once a Sol which can be used in these 2 classes. This will speed things up as well. Plus the 2 Util classes probably should be combined.

**Comment by mokun** [comment]
>  hence the inventory changes. 

Because the price/value point of goods change from time to time, by the time the drone arrives at the destination settlement, the goods that the origin settlement wants to buy may not be available or the price has changed. 

So we actually need to spell out clearly the terms the two parties used for negotiation.

We should give player options to choose what terms being agreed upon as well.

> Plus the 2 Util classes probably should be combined.

Yes.

**Comment by bevans2000** [comment]
The concurrency issue in the Delivery/Trade logic is too big for this Issue. Has a dedicated issues now #506

**Comment by mokun** [comment]
> Sometime it calculates the good value for a selling settlement which is under the control of a different Thread but that Thread is doing an local Load/Unload task and hence the inventory changes.... I think the way forward is for each Settlement to calculate an 'Inventory Audit' once a Sol which can be used in these 2 classes

Let's also create some preference settings for the player to select and change on the negotiation.  

This way, all the assumptions are made clear and the player knows what to expect. 

Now it's all done by whoever wrote the code and it seems complicated to understand whatever underlining rules are being used in a negotiation.

e.g. If settlement S1 is selling items A, B and C to settlement S2 and settlement S2 is selling resource D, E and F to S1. 

So in this delivery, S1 sends drone 1 to S2. However, upon arrival, S2 has already produce item C. So S2 will buy item A and B. 

Q1: Is this allowed for S2 to decline receiving item C ?

Also, if items A and B's prices has changed much (they could have gone up or down either way) since then. 

Q2: Should S1 update the selling prices on items A and B ?

So we could design an trade panel to allow these options to be pre-checked or unchecked.
