### ISSUE TITLE
Sleep Time table not rendered correctly

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#493]
**Describe the bug**
- one of the settlers does not have the sleep time table rendered beyond mission sol 5.

![image](https://user-images.githubusercontent.com/1168584/140010906-3f6dc6fb-a79c-4941-a14a-d538d6f6b505.png)

**Comment by bevans2000** [comment]
We only record the last 5 sols of sleep time to limit memory consumption. This must be a bug in the UI not updating correctly.

**Comment by bevans2000** [comment]
The logic in the SleepTableModel is correct. I think the problem is some update events are getting lost and the JTable does not update. Why do we hold so many Unit Windows in the MainDesktop class? Why don't we remove them once the Unit diaglog is closed? This has the potential to consume a lot of memory.

**Comment by mokun** [comment]
> Why don't we remove them once the Unit diaglog is closed? This has the potential to consume a lot of memory.

Sure. But if we delete each window when done, next time when opening it, it would take cpu resource to recreate them, right ? 

There should be a tradeoff in between cpu and memory.

By the way, the `Buildings` Tab of a Settlement Window is not responsive and its UI takes a short while to build.

![image](https://user-images.githubusercontent.com/1168584/141658506-14ed4068-3d9f-4a90-8b79-8c818a29c3fb.png)

Is there a way to optimize the construction of those BuildingPanel class ?

**Comment by bevans2000** [comment]
Well the unresponsiveness is because all the building tabs are constructed upfront. The UnitWindow in the UI is a very "fat" UI and consumes a lot of memory. Personally I don't use the UnitWindow because of these problems plus the updating is inconsistent. Sometimes it updates and sometimes it does not.

**Comment by mokun** [comment]
> Well the unresponsiveness is because all the building tabs are constructed upfront.

Yes. We've got rid of the Building tab in Settlement Unit Window already in v3.4.0.
