### ISSUE TITLE
Can't save the game

### ISSUE THREAD

**Issue by EmilPetecki** [mars-sim/mars-sim#60]
I don't know what the issue is but when I'm trying to save the game, the bar keeps loading and doesn't actually save the game in any way. How can I fix that?

**Comment by mokun** [comment]
Hi EmilPetecki, 

can you give details so that I may duplicate your situation ? 
are you running preview 8 ? on what OS platform ? does it happen all the time only in a particular case ?

**Comment by Banydman** [comment]
I found the same issues running on windows 10, but found the reason to be that I had Java 8 32-bit version installed. Uninstalling that and getting a 64-bit version going fixes the endless saving issue.

**Comment by mokun** [comment]
We have since resolved another bug that has to do with loading a saved sim. 

Can you guys try build 4255 at https://www.dropbox.com/s/zukd69gypoumwpo/4255.7z?dl=0 ?

It resolves the loading issue.

**Comment by mokun** [comment]
I've resolved in this [r4266](https://github.com/mars-sim/mars-sim/commit/d1b7caeb2629297c34bb0c96a73006c2d02140d9)

It has to do with another loading problem due to wrong static class being overridden during deserialization. 

So now, there is no more saving and loading issues.

With regard to setting up the java VM in windows 10, I always check the java version it will use by opening a command prompt and typing in `java -version` to double check. Setting up the correct path in the `Path` Environmental variable is tricky. Do take a look at `Java VM Setup` in README.md if it troubles you.

Let me know if you run into any issues.
