### ISSUE TITLE
Make BuildingType an enum class

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#613]
**Is your feature request related to a problem? Please describe.**
1. Currently, buildingType in Building is a string.
2. We have been matching and comparing this string excessively everywhere.
3. buildingType simply depicts a type of building.
4. However, the disadvantage is that this would prevent mars-sim from allowing players to create custom-made buildings in run-time in future since each building would be tied to a building type enum.

**Describe the solution you'd like**
1. Convert buildngType into an enum.

**Specifications  (please complete the following information):**
 - pre-3.4.0. build 6877

**Additional context**
1. On the other hand, we still BuildingTemplate class and BuildingSpec. 
2. Each building also have a generic name which is just the combination of its building type and a number (e.g. EVA Airlock 2)
3. We should allow players to rename the name of the building.
5. We may need to be careful what to put in toString() of Building. Would methods still be using toString() when it should be using building type comparison ?

**Comment by bevans2000** [comment]
I'm not sure about this because the Building in just a collect of Functions defined by the XML. It should be possible to create new Buildings with new combination of Functions without coding.
Another way of looking at this is where are we comparing the String building type. In fact once a Building is created why do we need the building type at all.

**Comment by mokun** [comment]
> I'm not sure about this because the Building in just a collect of Functions defined by the XML.

Perhaps we'll look into specific cases to see if building type still serves a purpose.

For instance, we have that ASTRONOMY_OBSERVATORY static string in Building.

In case of the astronomy observatory, it is an standalone that we must consider it as a special case when it comes to computing some walking tasks. 

May be in future, we would just give the ASTRONOMICAL_OBSERVATION FunctionType to another building.


But for now, it's quite important to

**Comment by bevans2000** [comment]
I think we should aim to reduce the reliance on the static Building strings.

**Comment by mokun** [comment]
Also, we have methods that compare if a building is a tunnel or hallway. May be we create a boolean value to see if this building is a connector or not. boolean value is faster than an integer/enum. But each building will equally need to have a true/false value.

In LabelMaplayer is where we could think of using building type enum to help identify and thus simplify the matching effort that runs on Java2D. 

But may be we can think of other alternative ways.

**Comment by mokun** [comment]
> I think we should aim to reduce the reliance on the static Building strings.

Agree. And that's why we have this thread to see if giving an enum building type to each building object is warranted.

**Comment by bevans2000** [comment]
> Also, we have methods that compare if a building is a tunnel or hallway. May be we create a boolean value to see if this building is a connector or not. boolean value is faster than an integer/enum. But each building will equally need to have a true/false value.
>

I don't understand why we need to check for tunnels and hallways. I must look at the code to see why.

**Comment by bevans2000** [comment]
I've had a look into this last night and have an idea I would like to move forward with to remove the hardcoded string but keep flexibility of the XML and user defined BuildingSpecs.

- The current Building.buildingType is badly names because it is actually the BuildingSpec name; but it's too much work to change this
- Create a BuildingCategory enum that would replace the use of the string comparing in most cases, e.g. CONNECTOR, WORKSHOP, LAB. This represents the primary purpose of a BuildingSpec.
- This drives the UI rendering of labels etc and helps positioning
- BuildingCategory can be derived from the combination of Functions in a BuildingSpec.
- The derived BuildingCategory can be overridden in the XML, e.g. LanderHab has many Functions
- Added a min & max distance property to the BuildingSpec to control the position of Building instead of hardcoded values
- Min & max distance is optional in the XML with defaults pre-defined.

A side effect is the logic will no longer be reliant on the building name and hence we can remove the redundant nickname property and allow users to just change the Unit name directly. The nick name field is a bug bear of mine.

**Comment by mokun** [comment]
> A side effect is the logic will no longer be reliant on the building name and hence we can remove the redundant nickname property 

But I was going to say it wasn't redundant per se and we still need a string to hold the nick name of every building being created.

> and allow users to just change the Unit name directly. 

Yes. That will be really great !

```
	<building type="EVA Airlock" width="6.0" length="4.0" base-level="-1"
			wear-lifetime="3340000" maintenance-time="50" room-temperature="22.5" base-mass="15">
		<description> The EVA Airlock is a node to be attached to building for giving direct access
			in performing EVA operations.
		</description>
		<power-required base-power="0.5" base-power-down-power="0.05" />
		<functions>
....

```
In the buildings.xml above, we have `type="EVA Airlock"` and that's where the so-called `building type` came from. 

But in order to distinguish between another EVA Airlock building in the same settlement, we need to append a number at the end of the building type. 

Thus we now have EVA Airlock 1 and EVA Airlock 2 and they are conveniently called the nick name of the building. We were talking about allowing players to change it.

**Comment by mokun** [comment]
Also, in terms of starting a new sim, currently, it seems convoluted. 

The SettlementConfig reads `settlements.xml` and create BuildingTemplate.

At the same time, BuildingConfig reads `buildings.xml` and create BuildingSpecs.

**Comment by mokun** [comment]
> If no logic depends on name having a defined format then Building name can be anything. Hence I see no need for the nick name field anymore. 

So let's go back to the definition, back to how we define what "building name" is.

To me, intuitively speaking, *EVA Airlock* means a building type. But *EVA Airlock 1* is a designated name given to a building that inherits the *EVA Airlock* building type. 

And this designated name is nickname.

From player's perspectives, say if I have 2 inflatable greenhouses, it'll be more convenient to call each one with a different name. 

So if we add in more ability for players to customize a building in future - which will be a big project itself, they may want to plant a lot of attractive flowers and less food crop in it for the expressed purpose of making the settlers feeling lively and appreciable.

In that case, the player decides to change this "Inflatable Greenhouse 1" to be called "Hanging Garden", just so it matches its function.
 
So to me, "Hanging Garden" is a nick name string for identifying that greenhouse.

**Comment by mokun** [comment]
> Currently it is needed because Building Name HAS to have a defined format for some of the logic to work; particularly in the UI Settlement View.

Do you want the **nick name** string of a building object` to be the same as the **name** of its super class `Unit` ?

Or do you want the **building type** of a building object to be the same as the **name** of its super class `Unit` ?

Btw, it's very good to create the BuildingSpecs class to store everything. Thanks for that conversion last year.

**Comment by mokun** [comment]
> No I'm saying why have the nick name at all? We can put the _EVA Airlock 1_ & _EVA Airlock 2_ directly into the Unit name field. I

i see what you mean.  You want to delete the nickname string field in Building and let the nick name of a building object to be picked up by its superclass Unit's name field.

**Comment by bevans2000** [comment]
Exactly. I think this will make things better and allow the user to change the Unit Name.

**Comment by bevans2000** [comment]
@mokun I'm working on a reworking of the ```BuildingConfig``` and how ```Function``` classes use the configuration. This will help resolve some inconsistencies in the approach on how we build/configure ```Building```. It turned out to be bit more of a change than I planned so I've pushed it to a branch to work though the remaining changes before 
This result will be a cleaner design and better separation..
I've noticed that the ```Heat``` class has a lot of using the building type name as derive the logic. I'll tackle this to remove the dependency on Building Type name,

**Comment by bevans2000** [comment]
To solve the issue in the ```Heat``` class using the building type name we need to think what it trying to achieve. The logic is actually identifying the construction type of the building based in the type name. Then it calculates heat loss gain accordingly. So I'm going to just add a new Construction property to the building spec, e.g SOLID, INFLATABLE, SEMI-SOLID. 
This will actually help in another place where we use wall thickness as well in meteorite strikes damage.

**Comment by mokun** [comment]
> e.g SOLID, INFLATABLE, SEMI-SOLID.

Yes in Heating class, it does seem like we can divide all buildings into at least these 3 types.

Also, back then, I tried to manually fine-tune heatGainEqiupment to have different values for different class of buildings.
