### ISSUE TITLE
A few Questions

### ISSUE THREAD

**Issue by AloysiousTasch** [mars-sim/mars-sim#633]
Hello,

I believe I have a few questions about the sim. I don't know if it is a bug, but I am having some issues and the wiki didn't have much info on them. I also figured that putting the questions all together would be better than posting four different "issue" posts.

1. Resupply missions - I tried to launch one out of curiosity but when I did it didn't appear in the main window nor anywhere else. I believe I might be timing it wrong. Also, the month tab has random words in it. Perhaps I am missing a piece to the puzzle.

2. Missions - I also attempted to launch an ice prospecting one, but when I got to the "select a rover" tab nothing came up despite the fact that I have an explorer rover that should be able to do the work. I believe that my astronauts just don't have high enough skill levels for this, and it is impeding the mission. Is there any way to change an astronaut's skills, and do they raise as they do work inside and outside of the hab? (Writing mission report, collecting local regolith). And, if I want to raise them even more, can I tell astronauts what to do some how such as in the sims 4? I'm used to that game, so it is sometimes difficult and annoying to follow them around and watch them "read/sleep/play a holo game/connect with friends and family" 90% of the time.

3. Construction - When I select a building site do I get to choose where it is? The Phase 2 and 3 bases of course have more modules, so if I want to build more will they appear in the preformed pattern that will lead to phase 2 and 3? Also, on a resupply mission if I order a hab module do I have to order a hallway piece as well for it to connect?

4. Astronauts - Can I change the attributes to an astronaut or is it randomly selected and unchangeable? I'm just curious about this question, as it is fun to play with the pre-made groups. Also, I was wanting to know if I could change their role. They have a job, such as botany, but I can't change the box below to something like commander, safety specialist, science specialist, etc. Right now, my botanist is collecting regolith and my engineer is being the botanist.

I may have to ad onto this or post another issue page as I continue on with the sim. I apologize for having so many questions. It seems like a great sim but I'm just having difficulty exploring it with limited information.

One more thing: is it normal for me to have to launch the game from a "cmd" page? I copy and paste the swing jar file into it and press enter, and a new page of MSP appears. Then I have to type in numbers, (1 for starting new game, 2 for loading saved, etc.). and more to further go on. Finally, when the game launches, it pulls up another page with light blue text with "marsnet>" that allows me to change the speed, pause/unpause, etc. Configuring the base and editing the crew is different from the screenshots on the main page, but this may be due to a different device. However, I am not bothered by this and personally I like it better. I just want to know if this process is normal for other simmers.

Thanks,
Aloysious

**Comment by mokun** [comment]
> Resupply missions - I tried to launch one out of curiosity but when I did it didn't appear in the main window nor anywhere else. I believe I might be timing it wrong. Also, the month tab has random words in it. Perhaps I am missing a piece to the puzzle.

Hi @AloysiousTasch ,
Let's me try to answer one at a time here.

Each resupply mission (sent from Earth) currently takes about a duration of 60 sols to arrive on Mars. 

This standard 60 sol transit is definitely NOT taking advantage of using Hoffman Transfer to save energy to travel, nor do we account for the actual orbital mechanics, i.e. the relative position between the earth and the Mars.  

We assume astronauts want to get to Mars as quick as possible to avoid unwanted radiation and we consider 60 sols as the minimum for now.

We could later add in the astrodynamics and it would depend on the starting date and the type of transfer orbit.

**Comment by mokun** [comment]
> Also, the month tab has random words in it. Perhaps I am missing a piece to the puzzle.

Which random words ? Are you referring to those unique Martian month names ?
e.g. *Adir* is the 1st month of Mars in a year. So it means January on Earth.

Also, on the Martian calendar panel on top right of the main window, there's actually has a wiki link on the Timekeeping. 

![image](https://user-images.githubusercontent.com/1168584/179823531-85a22d98-616f-44b9-a0fe-a11ddc6e9fbe.png)

If you click on it, it will open up your browser and go to this [page](https://github.com/mars-sim/mars-sim/wiki/Timekeeping).

**Comment by mokun** [comment]
> Resupply missions - I tried to launch one out of curiosity but when I did it didn't appear in the main window nor anywhere else. 

I tested the Resupply Tool by sending in a few buildings and it doesn't have issues.

![image](https://user-images.githubusercontent.com/1168584/179859581-dabc28cf-5e93-47e8-b104-eff5c4dfcd2d.png)


First, we didn't fully enforce the 60 days transit rule. 

Even though the `Sols Until Arrival` combobox starts at 61 days (in green box as shown) afterward, one can *outsmart* it by clicking on the `Month` combobox and change it from the month *Coan* back to month *Adir*.

Btw, that the very 1st day on Mars is 00-Adir-01. On Earth, it would be Year-Month-Day, such as 2022-Jul-19.  On Mars, it's Orbit-Month-Day. 

Second, there's also issues with the refresh and showing up of the new mission I just created. It doesn't always show up right away on the top left box 'Incoming Transport Items'.

If I save the simulation and quit and load the simulation again, it would show up.


Third, there's an issue with being too far away in placing a new building on an existing settlement in a resupply mission. It was by default placed at least 50 m away and so the hallway cannot be bridging the new building and any existing building.


Thanks for the heads up and we'll fix these bugs.

**Comment by mokun** [comment]
> Missions - I also attempted to launch an ice prospecting one, but when I got to the "select a rover" tab nothing came up despite the fact that I have an explorer rover that should be able to do the work. 

Q1: what's # of settlers in this settlement ?
Q2: which version/build of mars-sim are you running ?

See pic below in my`Schiaparelli Point` settlement with 24 settlers, there's a number of available vehicles. 

![image](https://user-images.githubusercontent.com/1168584/180501873-8a398e5f-1fff-40ac-83c0-b1d50edfcd97.png)

In fact, there's a total of 3 Explorer Rovers.

**Comment by mokun** [comment]
> 2. Missions -... I believe that my astronauts just don't have high enough skill levels for this, and it is impeding the mission. 

We have algorithm whenever someone was doing a mission planning.  Each mission will select from the best candidate as much as possible and Yes it's based on skills and experiences. But it doesn't those worst candidates won't be selected since it's just a priority thing, just like in real life.

> Is there any way to change an astronaut's skills, and do they raise as they do work inside and outside of the hab? (Writing mission report, collecting local regolith). 

Yes, each time a settler performs a task, it accumulates experience/skill points and labor time and over the time, they will get promote to the next skill level and become more productive and effectively in performing the same tasks.


> And, if I want to raise them even more, can I tell astronauts what to do some how such as in the sims 4? 


Yes, we've been experimenting with giving a settler an explicit order to perform a task in the *Command Mode* only for the time being but we got distracted with other features/improvement we want to work on.

So if you like to see certain features, do open a new discussion/issue and talk only about that whatever ONE THING is. This is we can stay focus on getting one thing done at a time.
 
> I'm used to that game, so it is sometimes difficult and annoying to follow them around and watch them "read/sleep/play a holo game/connect with friends and family" 90% of the time.

Sure. We have created 50+ tasks already available but we want more diverse activities and more visible tasks for settlers to do. 

In real world, we can do whatever we want but in simulation we do have hand crafted and test out each task we can think of.

https://github.com/mars-sim/mars-sim/issues/625 is one of those developer's thread for discussing others Java class and methods that would expand the capability of mars-sim to conceptualize and implement projects or activities since in mars-sim, we only have what we called *Mission* and *Task*.

Do feel free to suggest what features you would like to see and perhaps discuss any design and development approach with us.

Interestingly, mars-sim have been designed from the ground up to be an unique simulation (not quite a strategy game) that is self-running. So in principle it doesn't require much of player's attention.

So mars-sim isn't one of those typical micro-management approach in some strategy games out there.

However, this approach can be boring to gamers. 

So we have agreed in the past that we want to have more interactivity and opportunity for player to make decisions that will impact the development of the settlements in mars-sim. 

So we have wanted to work on building more macro-management types of decision for players to have a say on what they envision their settlement will look like years down the road.

But we are not quite there yet and please do by all means chime in and discuss how to get there and any future development directions of mars-sim.

**Comment by mokun** [comment]
With regard to tasks, I've edited this [wiki](https://github.com/mars-sim/mars-sim/wiki/Tasks) to incorporate more info on the concept of Task and Meta Task.

Also, this [wiki](https://github.com/mars-sim/mars-sim/wiki/Missions) talks about the concept of Missions specifically.

Feel free to point out any things you have in mind particularly.

**Comment by mokun** [comment]
> Construction - When I select a building site do I get to choose where it is? 

In the past, if a player starts a construction mission and would like to choose a construction location with keyboard/mouse on a settlement map, there were too many unresolved bugs with dragging/moving the site to a desire position. Therefore we had to disable that ability. 

Currently, the algorithm would determine the location. We apologize that it doesn't always give the most optimal position on the map.

We'll return back to this issue soon. 

> The Phase 2 and 3 bases of course have more modules, so if I want to build more will they appear in the preformed pattern that will lead to phase 2 and 3? 

The collision algorithm is supposed to detect if any existing positions on the map has been taken and have a building on it and avoid that area. 

> Also, on a resupply mission if I order a hab module do I have to order a hallway piece as well for it to connect?

If a player starts a Resupply mission, he will need to not such choose a building to be sent to Mars, he will need to send a hallway as well.

I think you made a good point. If the player forgot to ask the mission control to send a hallway, the player should be able to use Construction mission to build one instead, provided that all the construction material are ready. 

Starting a Construction mission to build a hallway will involve first building a 'foundation', then a 'frame' and at last a hallway 'building'.

**Comment by mokun** [comment]
> Astronauts - Can I change the attributes to an astronaut or is it randomly selected and unchangeable?

Before the beginning of your new simulation, you can change the attributes of your crew by directly changing them in the xml files (not as recommended), or by using the Scenario editor.

> I'm just curious about this question, as it is fun to play with the pre-made groups. Also, I was wanting to know if I could change their role. 

During the simulation, you can also request changing their job and role in the Person Window.

![image](https://user-images.githubusercontent.com/1168584/182001938-4757aa74-67da-4bc5-9ff8-2bac0fdf0937.png)

> They have a job, such as botany, but I can't change the box below to something like commander, safety specialist, science specialist, etc. Right now, my botanist is collecting regolith and my engineer is being the botanist.

Having said that, however, it also depends on what's called the *Job Prospects* of that particular person and the *Job Demand* in that settlement.

The algorithm will help the settlement to balance between what's its needs and what the settlers or you as the comander wants. 

For instance, say settlement A has 12 people and it has only one botanist. 

But it's really in need of two botanists because there are two greenhouses, instead of just one.

Let say also that there's no Gardenbot to help out.

Chances are it will switch another person's job (who used to be trader) to become botanist to fulfill that needs. 

Rest assure, the algorithm will pick the best candidate to be botanist.

**Comment by mokun** [comment]
In order to use `Scenario Editor`, choose 1, 2, and 1 in the Console Main Menu as follows: 

```
 ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------

                          * * *   Main Menu   * * *


0. Exit
1. Start a new Sim
2. Load a saved Sim
3. Change screen resolution

Choose an option : ​1

Starting a new sim...

 ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------

                        * * *   Mode Selection   * * *


0. Exit
1. Command Mode  (Experimental only)
2. Sandbox Mode

Select the Game Mode: ​2

Go to Sandbox Mode...


           * * *  Sandbox Mode - Crew and Scenario Selection  * * *

0. Exit
1. Open Scenario Editor
2. Enable/disable crew loading (currently Enabled)
3. Proceed to start the sim
4. Back to the previous menu

Note 1: By default the loading of crews is Enabled. Choose 2 to enable/disable.
Note 2: The Console Editon does not come with the Scenario Editor.

Enter your choice: ​1

Loading the Scenario Editor in Swing-based UI...
```

![image](https://user-images.githubusercontent.com/1168584/182002955-ba30383b-22a8-4d52-9c9c-8e2aaa30f546.png)

In the right hand side of the `Scenario Editor` (aka Simulation Configuration Editor), click on **Crew** button to start the `Crew Editor`.

![image](https://user-images.githubusercontent.com/1168584/182002993-d28a1654-815b-4537-b012-0126a753f36f.png)

Initially, mars-sim comes with *Alpha Crew* with up to 5 standard team mates.

After you have edited them, you can click `Save As` button at the bottom to save it as your newly created crew, such as Bravo team, etc.

Next time when you start a new simulation, you can always come back here to load your Bravo team.

**Comment by mokun** [comment]
> It seems like a great sim but I'm just having difficulty exploring it with limited information.

We have wanted to expand on our [wiki](https://github.com/mars-sim/mars-sim/wiki) so that everyone can understand better. There are already 71 pages written on mars-sim. They need to be continuously updated as  new features are being implemented.

Do feel free to browse them through and discuss with us and cite the page you may have questions on.

**Comment by mokun** [comment]
> is it normal for me to have to launch the game from a "cmd" page? 

Yes to me this is also my normal way of starting mars-sim. I want to be able to have access to the log statement it generates to see if it runs into any issues.

> I copy and paste the swing jar file into it and press enter, and a new page of MSP appears. 

Correct. For windows users, if starting mars-sim by clicking on the jar, they will have to rely on the Swing UI and won't have the logs shown.

> Then I have to type in numbers, (1 for starting new game, 2 for loading saved, etc.). and more to further go on

Sorry about this approach. We used to have JavaFX UI in v3.1.0 but removed it in v3.2.0 because the incompatibility of some JavaFX and Swing UI elements. 

So for now, it's bit backward with the use of the text console to choose how to start mars-sim.

In future, we'll streamline it.

So, are you a linux user and prefer text interaction ?

**Comment by AloysiousTasch** [comment]
Hello again.

I apologize for the delay, but I have been extremely busy with the start of high school and several other things. Anyways, thanks for the new information. The stuff on the calendar and resupply tool is extremely informative, but the mission option is where I still have errors in. Also, I am running version 3.3.0, (hopefully the latest version, but I'm not sure), on a surface pro-4.

In my most recent save, I loaded up a sim with only Schiaparelli Point. When I attempted to start up a mission, I could get all the way to the "select a rover", but despite the base having the necessary rovers they didn't appear in the menu. 

I just loaded up a sim with all of the bases, and now it has a bunch of "proposed" research studies, but they are not approved. I am assuming that the lack of this in my first save is an error, but I have no idea. 

I'm still reading over the other comments (also looking very promising), but I do have one question: When saving a game, where should I put the save file? It gives me several options. I'm trying to upload a screenshot but something isn't working. I'm not exactly tech-savvy. 

Anyways, thanks so much for continuing to add on information, as I really do appreciate everyone making a free simulation project that accurately depicts life on mars. 

Thank you!

**Comment by AloysiousTasch** [comment]
Also, I just attempted to set up a mission for ice prospecting, but unfortunately it has the same error as when I tried previously, with no rovers popping up as available.

**Comment by mokun** [comment]
> Also, I just attempted to set up a mission for ice prospecting, but unfortunately it has the same error as when I tried previously, with no rovers popping up as available.

It seems v3.3.0 has a bug that stops player from manually creating a mission.

Let's download [Build 6975](https://github.com/mars-sim/mars-sim/releases/tag/r6975), it's a new but unofficial build of mars-sim. The problem should go away. Thanks for pointing that out.

**Comment by mokun** [comment]
> a bunch of "proposed" research studies, but they are not approved. I am assuming that the lack of this in my first save is an error, but I have no idea.

When a person proposed a research study, he has to find collaborators and assistants. He would send out invites to appropriate people that's based on the topic of interest. 

If he can't find one, this study could get aborted.

In this long [thread](https://github.com/mars-sim/mars-sim/issues/144) we ask for ideas in redesigning how mars-sim should model scientific studies and what kind of impact the simulation and what we would like to see. 

May be you can chime in and contribute to that melting pot of ideas.

**Comment by mokun** [comment]
> When saving a game, where should I put the save file? It gives me several options. 

It's up to you where to save the simulation and it won't matter.

To me, I use Windows 10, and save it at the default location inside my home directory.
 
Most people hit 'save' and save it as `default.sim`

**Comment by mokun** [comment]
Other times, if the picture file is already saved and is located in a folder, I would simply **drag and drop** that file onto GitHub's text area of the conversation thread. 

Then it will automatically upload that picture and attach it to the conversation.

**Comment by mokun** [comment]
So there is at least these two aforementioned ways of attaching a picture, depending on where the source of your picture is at.

**Comment by AloysiousTasch** [comment]
Excellent! Thank you so much for the information. The screenshots are irrelevant now, but I will definitely use that feature in the future.

I would love to suggest features. I have a vague and broad group of ideas right now, but as I learn more about the sim, I will definitely refine that.
