### ISSUE TITLE
Downloading Build 6975

### ISSUE THREAD

**Issue by AloysiousTasch** [mars-sim/mars-sim#677]
Hello again,

You all were probably expecting this, but I am having difficulty downloading build 6975.

It has instructions on the download page, but I so far, I have not been able to follow them successfully.

I apologize for still being helpless, but could someone help me out?

Thanks (again)
Aloysious

**Comment by Paculino** [comment]
Are you having trouble starting/loading a sim, the UI, or is the download itself? You shouldn't have any issues with Java now since you could open 3.3.0

**Comment by AloysiousTasch** [comment]
It was actually mostly installed by my father, who has experience in computers, but he hasn't had the time to look at this again and I don't want to bother him. I was able to unzip the file to a folder named "mars-sim-r6975" but going on from that nothing is working. Is there something I'm missing before I launch it from CMD?

**Comment by mokun** [comment]
In this [Release page](https://github.com/mars-sim/mars-sim/releases), simply click on `[6975_swing_java11.jar](https://github.com/mars-sim/mars-sim/releases/download/r6975/6975_swing_java11.jar)` (see yellow circle below) to download this jar file.

![image](https://user-images.githubusercontent.com/1168584/188288434-66ed7963-5923-4d66-a47e-d8648fd46a9d.png)

Once it's done, it should be in your window's `Download` folder. 

Feel free to drag and drop it to a designated folder you desire to keep it. 

To me, I created a folder called `6975` to keep the jar file.
![image](https://user-images.githubusercontent.com/1168584/188288560-2ab95f66-121c-4a7a-923e-72f1aa95e1c6.png)

Inside this folder, I typically open a DOS-like command prompt window and run this jar file by typing `java -jar 6975_swing-java11.jar` and hit enter.

![image](https://user-images.githubusercontent.com/1168584/188288677-5561bc6c-e238-4d6e-bc10-18add1075d40.png)

**Comment by mokun** [comment]
> I was able to unzip the file to a folder named "mars-sim-r6975"

Since it's already in jar format, it actually doesn't need to be unzip again.

There are 2 ways of starting the jar file.
1. Simply double click on the jar file to start it - it doesn't requires any typing to start mars-sim
2. Use Command Prompt/Terminal to start it - it requires going into that folder using the command prompt window and typing up `java -jar 6975_swing-java11.jar` and hit enter

**Comment by AloysiousTasch** [comment]
Unfortunately, I've already tried that method and it doesn't work. I believe it has something to do with the fact that the description of your version of the file says: "executable jar file" while mine just says: "JAR file". Is the problem from that? It also doesn't have the same logo, as mine has the notepad logo.

I apologize for making you all work so much, and I really do appreciate it.

**Comment by Paculino** [comment]
Can you right-click it and Open_with> Platform Binary instead of notepad (which seems to be the default for you)? You may also wish to select "Choose Another App" instead of platform binary so you can change the default app to open it with to make it easier later.

**Comment by mokun** [comment]
> select "Choose Another App" instead of platform binary so you can change the default app to open it with to make it easier later.

@Paculino ,

Yes. Thanks for pointing that out for @AloysiousTasch. 

It's easy to change the target application that links to a file extension.

e.g. In my friend's laptop, he link all the *.pdf files to a browser, instead of the Adobe Reader. This way, he has to open a pdf file in the browser. But in my laptop, I don't do it this way.

In @AloysiousTasch case, when you install Java VM on your computer, make sure you use the MSI version because it comes with an installer that will automatically updated the jar extension to the Java VM that you are installing. 

If you download only the standalone version of Java VM, then you will have to set things up manually.

Let us know how things turn out and don't give up. These things can be resolved.

**Comment by AloysiousTasch** [comment]
Thanks for the  new information.

When I tried to open it with platform binary, the program opens for about a second before disappearing. At this point, I really do not know what is happening.

Also, is Java VM necessary for the program to run?

**Comment by mokun** [comment]
> Also, is Java VM necessary for the program to run?

Yes, sorry, it's critical that a Java version 11 Virtual Machine (JVM) be installed ahead of time in your computer. 

For now, mars-sim requires VM and runs on top of it. 

In future, we'll try to make a all-in-one mars-sim JVM bundle. 

We reccomend downloading openJDK 11.

One very common issue about setting up Java VM is having multiple versions of JDKs already on a computer. Obviously this could potentially create conflict.

Your Path variable in Windows 10 will need to be set to point to the Java 11 JDK that you install for running mars-sim.

mars-sim is not fully compatible with Java 17 yet. 

So for those have Java 17 installed, they'll need to switch to Java 11 by changing the Path variable in order to run mars-sim.

It's a little bit of hassle but not that much :D

**Comment by AloysiousTasch** [comment]
Ok, I'll try that! Thanks for helping out, and I will comment later for the outcome.

**Comment by AloysiousTasch** [comment]
Also, do you have any idea on what the old java file would look like? I've searched through my downloads but haven't found anything interesting.

**Comment by mokun** [comment]
> old java file

do you mean the jar file ? or the JDK installer that you downloaded ?

**Comment by AloysiousTasch** [comment]
JDK, I believe. I also think I found it. Is it under Amazon coredetto? I would upload a screenshot, but I still can't, and I'd rather not try to make it work for the next fifteen minutes.

**Comment by AloysiousTasch** [comment]
Should I uninstall that and reinstall java 11 JDK from oracle?

**Comment by mokun** [comment]
> Should I uninstall that and reinstall java 11 JDK from oracle?

It doesn't matter.

For those in open source movement, they prefer pure open source software and thus choose only OpenJDK and would never use Oracle JDK. 

There are a dozen of OpenJDK out there available for you to choose. They're super similar.

One of the OpenJDK out there is Amazon Corretto. I myself use [Bellsoft/Liberica JDK](https://bell-sw.com/). 

The important thing is whatever flavor you choose, download only Java 11 since it's the version of Java that's compatible with mars-sim.

**Comment by mokun** [comment]
> Should I uninstall that and reinstall java 11 JDK from oracle?

I should say that if you have OpenJDK 17 version of Amazon Corretto  then it's better off you uninstall it and download the OpenJDK 11 version of Amazon Corretto. 

This way, your machine only have one and only one version of Java (namely version 11) for mars-sim.

**Comment by AloysiousTasch** [comment]
I believe that I already have OpenJDK 11 amazon corretto, although I may install it again just to be safe. 

Once I have this installed, what should I do next? Are there any steps in between trying to open the file using java and downloading corretto?

**Comment by mokun** [comment]
If the JDK 11 is installed properly, you should be able to run mars-sim under command prompt so that you can see the log statements.

So I'm curious in the past, did you run mars-sim using command prompt ?

**Comment by AloysiousTasch** [comment]
Yes, I did run it through CMD, although my father configured it. I'm going to try to get him to take a look tonight, as this is approaching the edge of my knowledge.

**Comment by AloysiousTasch** [comment]
Hey again,

With the help of my father, we finally got it to work, but all of your recommendations were also helpful. Turns out it was just something to do with CMD, and the new way to download and launch it is much faster than the previous way. Also, the mission bug that I was experiencing in 3.3.0 is gone and I am just waiting for my proposed studies to be approved. So far, I do have some recommendations and possible issues, but I will put that in another issue post. 

Again, thanks for all the help.
