### ISSUE TITLE
modular dependencies versus distribution dependencies. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#68]
.
I was reading about [modular programming](http://webreference.com/programming/modular_programming/index-2.html) for something else which told me the reasons why we have dependencies under each module. 

Is there a possibility of having just a long list of dependencies right at the root or somewhere which has all the dependencies we need.  As shared in https://github.com/mars-sim/mars-sim/issues/40  each module seems to have its own pom.xml which tells the dependencies therein. 

If we have just one large pom.xml then for distributions it would be far easier to package. 

I know there was some movement or talk about that but dunno how far we went with it ?

**Comment by mokun** [comment]
Modular programming is a useful concept and it can mean a number of things.  

[The OSGi standard](https://www.osgi.org/) and Java's Project Jigsaw are both trying to make programming more modular but OSGi is broader and stricter. Not everyone adopts it. 

Since we have just moved to supporting Java 9, we are using Jigsaw transparently now. But we are NOT OSGi compliant.

Now you might have heard of the idea of [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell)

In terms dependency management, Maven is currently responsible for managing dependency in mars-sim. 

It has built-in ways to manage a few different versions of the same dependency such as common-io. 

Maven can show us if there are [circular dependency](https://en.wikipedia.org/wiki/Circular_dependency) issues that software developers need to resolve it.

Coming back to how we use Maven, in mars-sim, at some point after we adopted maven to structure the codes, we created 4 sub-modules (that are in active use). We sort of achieve "the separate of concern" this way. e.g. mars-sim-ui is responsible for building the UI. mars-sim-main is for starting the app, etc. 

If we are talking about user-generated package dependency, one example is that in mars-sim-main's pom.xml, we specify that mars-sim-main depends on mars-sim-ui and mars-sim-mapdata.

Because of that, we CANNOT in terms make mars-sim-ui depends on mars-sim-main in in mars-sim-ui's pom.xml. If we do, it will be a logical circular dependency error.

It's like if A and B are basic units, If A depends on B. then B CANNOT depends on A.

**Comment by mokun** [comment]
But if we are talking about outside dependency such as the use of junit 4.12.

We don't download junit over and over again for each submodule's pom.xml that reference it. It was downloaded once into /.m2 directory in our machine. 

When a sub-module needs it, it will go make a copy of its .jar and .class and save it in a dedicated path. 

When we compile mars-sim into a distribution package ready for release, there is only one copy of junit in that package.

**Comment by shirishag75** [comment]
> But if we are talking about outside dependency such as junit 4.12.
> 
> We don't download junit over and over again for each submodule's pom.xml that reference it.
> 
> Note that 3 of the 4 submodules needs it for code testing.
> 
> It was downloaded once into /.m2 directory in our machine.
> 
> When a sub-module needs it, it will go make a copy of its .jar and .class and save it in a dedicated path.
> 
> When we compile mars-sim into a distribution package ready for release, there is only one copy of junit in that package.

But that is exactly my point. What is being achieved here is having everything underneath .m2/ subfolder. This is not needed. 

Just to take the same example as you shared. Junit is already is Debian. And so is the case of many of the packages which are called and put in .m2/ folder . 

```
$ aptitude search junit
p   jmeter-junit                                         - Load testing and performance measurement application (junit mo
i A junit                                                - Automated testing framework for Java                          
p   junit-doc                                            - Document for JUnit                                            
pi  junit4                                               - JUnit regression test framework for Java                      
p   junit4-doc                                           - JUnit regression test framework for Java - documentation      
p   libtap-formatter-junit-perl                          - Perl module for converting TAP output to JUnit XML output     
p   python-junit.xml                                     - creates JUnit XML test result docs readable by tools such as J
p   python-junitxml                                      - PyUnit extension for reporting in JUnit compatible XML        
p   python3-junit.xml                                    - creates JUnit XML test result docs readable by tools such as J
p   python3-junitxml                                     - PyUnit extension for reporting in JUnit compatible XML
```

Now you could say that perhaps the version of junit we have in the repository is not correct but that could be done.  I have seen that most packages that are downloaded are also hard-coded in the pom.xml file 

```
 <!-- https://mvnrepository.com/artifact/org.luaj/luaj-jse : 311 KB 
	   	<dependency>
			<groupId>org.luaj</groupId>
			<artifactId>luaj-jse</artifactId>
			<version>3.0.1</version>
		dependency-->

```

Debian does the same thing using build-depends in debian/control file. See 

https://sources.debian.org/src/telegram-desktop/1.2.17-1/debian/control/

and if there is any package which is not in the distribution or isn't the right version than efforts are expended to do the right thing. 

As far as dependency hell is concerned, most people who have used Debian number of years are aware about it. This comes in way of packaging new applications and updating applications to new versions. 

For mitigation of dependancy hell, we use shared library transition and it has worked for us number of years. https://release.debian.org/transitions/ . 

This is not to say we are on top of the things all the time as we have 50k+ binary packages on around 10+ official and non-official hardware architectures but we try.

**Comment by mokun** [comment]
Perhaps there are legitimate reasons that these packages are kept separate.

The idea of sharing dll's is a big topic in Windows world.

If I write and distribute an app, I want everything self-contained.

From the developer point of view, I want to make my app reliable and as less dependent as possible on other elements, such as the health and well-being of other dependencies already in that machine.

I suppose if Debian can work out the details on how Maven handles dependencies, then the two can marry each other.
