### ISSUE TITLE
Allow UI to be used when simulation is paused

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#724]
**Describe the bug**
When the simulation is paused either manually or via a save, the UI is locked and nothing can be viewed. This is a hinderance.
Sometimes the simulation is paused to look at the state of various entities but this can not be done because the UI remains locked.

**Expected and unexpected behavior**
When a pause occurs the UI should remain active and usable. A decoration could be added to the toolbar to show it is paused but nothing else on the UI changes.

**Comment by mokun** [comment]
Yes. I find it very vital to be able to examine various UI elements when the simulation is on pause.

That's why we have the Pause Overlay checkbox on the bottom of the screen.

![image](https://user-images.githubusercontent.com/1168584/196043180-e6d90707-1e21-4eb8-bbee-7366d6d7be27.png)

When I uncheck that box, the big visual orange pause bar "||" at the center of the screen would disappear, indicating that the player may open any tools.

![image](https://user-images.githubusercontent.com/1168584/196042924-a684d30e-f692-49f6-9dce-52dd9f81fb7d.png)

Having said that, this approach of using the top layer swing ui window mode of mars-sim doesn't always work well. 

Sometimes the big orange pause bar doesn't show up, especially if I switch between mars-sim window and other windows often.

Also, the big orange pause bar has not been thoroughly tested in mac or linux.

**Comment by mokun** [comment]
In `MainWindow`'s init(), we have  
```
		// Set up the main pane
		mainPane = new JPanel(new BorderLayout());
		frame.add(mainPane);

		// Set up the jlayer pane
		JPanel jlayerPane = new JPanel(new BorderLayout());
		jlayerPane.add(desktop);
		// Set up the glassy wait layer for pausing
		jlayer = new JLayer<>(jlayerPane, layerUI);

		// Set up the overlay pane
		JPanel overlayPane = new JPanel(new BorderLayout());

		// Create a pause overlay
		createOverlay(overlayPane);

		// Add desktop to the overlay pane
		overlayPane.add(jlayer, BorderLayout.CENTER);

		// Add overlay
		mainPane.add(overlay, BorderLayout.CENTER);
...

		// Create overlay button
		createOverlayCheckBox();
		statusBar.addLeftComponent(overlayCheckBox, false);

```

We've been using weblaf's `FillOverlay` to turn on and off that big orange pause bar at the center of the screen.

```
	/**
	 * Sets up the pause overlay
	 *
	 * @param overlayPane
	 */
	public void createOverlay(JPanel overlayPane) {
		// Add overlayPane to overlay
		overlay = new WebOverlay(StyleId.overlay, overlayPane);

		Icon pauseIcon = new LazyIcon("pause_orange").getIcon();

        blockingOverlay = new WebStyledLabel(
        		pauseIcon,
                SwingConstants.CENTER
        );
        NoOpMouseListener.install(blockingOverlay);
        NoOpKeyListener.install(blockingOverlay);
	}

	public void createOverlayCheckBox() {
		overlayCheckBox = new JCheckBox("{Pause Overlay On/Off:b}", false);
		overlayCheckBox.putClientProperty(StyleId.STYLE_PROPERTY, StyleId.checkboxLink);
		TooltipManager.setTooltip(overlayCheckBox, "Turn on/off pause overlay in desktop", TooltipWay.up);

		overlayCheckBox.addItemListener(new ItemListener() {
		    @Override
		    public void itemStateChanged(ItemEvent e) {
		        if(e.getStateChange() == ItemEvent.SELECTED) {
		        	// Checkbox has been selected
		        	overlay.addOverlay(new FillOverlay(blockingOverlay));
		        } else {
		        	// Checkbox has been unselected
	                if (blockingOverlay.isShowing()) {
	                    overlay.removeOverlay(blockingOverlay);
	                }
		        };
		    }
		});
		// Disable the overlay check box at start of the sim
		overlayCheckBox.setEnabled(false);
	}
```

**Comment by mokun** [comment]
If the overlay pause bar doesn't work well in all OSes, we could certainly change it and replace it with something better.

Similarly, if it's too hard for player to notice the speed + and - switch at the bottom of the window, we could also move it back up to top right.

**Comment by bevans2000** [comment]
I didn't even know about the Pause Overlay checkbox. Then I'll give that a try .
