### ISSUE TITLE
Both Martian time and Earth time not matched up

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#800]
**Describe the bug**
- Both the Martian time and the Earth time label in Tool bar somehow trail behind the time from the Time Tool by a large margin.
- On "Sol : 1", the sol do NOT match up between what's shown in the calendar and the one on the toolbar and the one on the Time Tool.

**Java classes involved**
- MainWindow, TimeWindow

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/215296474-e6e194e0-2847-4c7a-9ee2-554ed6158ae0.png)

**Specifications  (please complete the following information):**
 - pre-3.5.0 build 7786

**Extra**
- The sol number issue is probably due to the conversion between the old Java calendar API and the new Java 8 Time API.
- Q1 : should the local machine time be used ? or the universal time should be used in the Earth time ?

**Comment by mokun** [comment]
@bevans2000 

The sol counter should have been shown as "Sol : 1" when sol 1 is already over.

**Comment by bevans2000** [comment]
Hmmm interesting. I'll check but they should be use the same methods.Unless they are different refresh rates.

Do you see useful having all 3 in the toolbar? I think maybe we just show the Mars time. The time tool can give the breakdown if needed

**Comment by bevans2000** [comment]
Right, the problem is due to the ```TimeWindow``` & ```MainWindow``` have different update frequencies on the Clock Listener. This means they can get updated in different pulses and hence show different times. I am going to consolidate the use if the CLockListener in the  UI such that it all hangs off a single CLockListener attached to the ```MainWindow```.  This centralised listener will update any child windows that need time updates. This is actually better as all windows will stay synchronised.

Relates to how we model time in #650. Ideally Earth & Mars time should be immutable objects with only the ```MasterClock``` being dynamic. Changes would then be event driven from the ClockListener.

**Comment by bevans2000** [comment]
I've had a light bulb moment. The ```ToolWindow.update``` method should take the master clock as an argument and this removes the need for specific windows to have custom clock listener. Net effect is that the UI will have a single clock listener, passing any updates to the various tools like it does already.
Second advantage is it will remove the need for some windows maintain a reference to the MasterClock as a attribute in the class.
