### ISSUE TITLE
remove log4j 1.2.17 and instead use Apache Log4j2 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#82]
See https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces 

http://logging.apache.org/log4j/1.2/

http://logging.apache.org/log4j/2.x/log4j-core/dependencies.html#Dependency_Tree - the new one.

**Comment by mokun** [comment]
mars-sim uses primarily the basic logging API from Java API (java.util.logging). I don't think I use log4j "directly" at all. 

However, log4j is there because some dependencies uses it. 

As a result, we'll have to include it in our binary.

This is a very common issue. The same situation happens with various versions of the same dll in an C++ Windows application.

**Comment by mokun** [comment]
Besides the fact that we don't use `log4j` in mars-sim, we created a custom class called 
[LogConsolidated](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/LogConsolidated.java) to deal with the cases when it's firing the same logging statement within a small period of time by bundling them together into one.

> e.g. 2018-10-31T13:53:16.2 (Severe) [x66] Storage at LivingAccommodations::generateWaste : (AR) No more room to store 1.36 kg of grey water (or storage space has not been initialized yet).

Closing this now.
