### ISSUE TITLE
Setting up Java

### ISSUE THREAD

**Issue by Sawaqedf** [mars-sim/mars-sim#832]
**Describe the bug**
- I am currently on Windows, I am trying to download mars for my course but after downloading, it's asking to open with "notepad". 
- The icon of the file also doesn't show the Java icon, it shows a bland page, and then a bunch of code when I open the program. 
- I currently have Java 19 and 20 on July computer. 

What should I do?

**Comment by bevans2000** [comment]
Are you trying to just run the simulation or look at the code and build it yourself?

If you want to build it then You need to install an IDE for java which will allow you to see the structure of the Java code. Two popular ones are:

- VSCode https://code.visualstudio.com/docs/languages/java. My preferred choice
- Eclipse https://www.eclipse.org/downloads/packages/release/2023-03/r/eclipse-ide-java-developers The choice of @mokun 

Both will work with Mars Sim.

**Comment by mokun** [comment]
@Sawaqedf 

First of all, you probably know mars-sim requires java to be pre-installed. In other words, it runs inside Java.

A "raw" Java application is in the form of a jarfile. e.g. ABC.jar

Second, can you test to see if other Java applications can be run on your machine ? 

If not, it means your last Java installation failed and perhaps that's why the jar extension was set to opening up a text file in the notepad.  If that's the case, do re-download Java 17 as a MSI file and double click it to re-install it. 

Third, assuming that you have already successfully installed Java 17 or above on your machine. 

There are two ways to run mars-sim.
1. Open a command prompt and type `java -jar xxx.jar`. You will see all the logs on the command prompt as it runs. It's good for debugging and it tells you a lot more on what's going on with the simulation.
2. Double-click the jar file to run it. You won't see any logs.

Let us know how it goes. Drag and drop some screen shots here if you like. Have fun !

**Comment by Sawaqedf** [comment]
Hello, I've been using Eclipse for a while now so I'm pretty sure other Java applications are working. I redownloaded java 17 as a Msi file and tried to open mars both ways, but I got the same results. Here are the screenshots for reference.![image](https://user-images.githubusercontent.com/129470969/229120378-f88f3eff-70ae-480d-a123-c110d2377983.jpeg)
![image](https://user-images.githubusercontent.com/129470969/229120414-5ea4a95f-f908-4207-bbe7-773c5c4e0b5d.jpeg)
![image](https://user-images.githubusercontent.com/129470969/229120429-c1f717f5-bd99-4c92-a297-1f85a762d80b.jpeg)

**Comment by Sawaqedf** [comment]
Do you mean this? I did this yesterday while searching on how to get the app working and still the same thing. I downloaded Mars4_5 from the Missouri State University website, I tried downloading the one you provided but nothing. How is this supposed to work exactly, am I supposed to just download it and get it to open? ![image](https://user-images.githubusercontent.com/129470969/229151979-52cdc98c-cdc1-47b4-80c9-368bb1f8f414.jpeg)

**Comment by mokun** [comment]
Can you type up `java -version` in a command prompt and post the picture of the result here ? 

I should have said that the last official version of mars-sim, namely  v3.4.1, can only be running on top of Java 11, and not yet on Java 17, 18, 19, 20, etc. The next release, namely v3.5.0, will support Java 17.

Have you by any chance followed through the detail instructions in setting up the Java Home directory found in mars-sim's readme.md  ? 

May I ask exactly at what point you find it not working ?

**Comment by bevans2000** [comment]
Well I don't know what has been downloaded from the Missouri State University but the official mars-sim is at version 3.4.1 and can be downloaded from the location in the previous comment. I would

1. Download the 3.4.1 release which will be a file called 3.4.1_swing_java11.jar. This will probably be in your downloads folder
2. Run a command prompt
3. Change directory to where your JAR file has been downloaded
4. Run java -jar 3.4.1_swing_java11.jar
5. The UI should then run and appear

**Comment by mokun** [comment]
http://courses.missouristate.edu/KenVollmar/MARS/

The screenshot you provided shows that the extension "jar" of the file `Mars4_5.jar` was associated with an application called NCHZipExpress.

I found this particular app  that you have installed at 
https://www.nchsoftware.com/zip/index.html

Can you uninstall it ?  It will continue to interfere with how you would run mars-sim and possibly other Java apps.

**Comment by mokun** [comment]
A lot of zipfile handling applications such as "NCH Zip Express" would allow you to unzip a jar file and see inside the content of a jar.  

If you installed them on your machine, clicking on a jar file would execute this zip handling app with respect to the jar, instead of letting Java VM to run the Java jar file directly. 

Just beware of that.

**Comment by Sawaqedf** [comment]
This is what I got! I thought I had deleted that application a while back but there was some residue, I deleted the residue but it's still the same thing. I might have to try doing it on another computer to see if it works.

![image](https://user-images.githubusercontent.com/129470969/229191236-db790a85-fced-4053-bcd3-95f869b68246.jpeg)

**Comment by mokun** [comment]
In order to run mars-sim v3.4.1, it's required that you have Java 11.

It won't run in Java 12-20.

But when v3.5.0 comes out, it will run on Java 17. I'm not 100% it will run on Java 18-20 yet. 

@bevans2000 
Have you tried pre-v3.5.0 on Java 18-20 ?

**Comment by mokun** [comment]
@Sawaqedf 

What you have currently in your machine is Java 20, you can always change it to pointing at a particular version of Java, such as Java 17, 18, or 19 by changing the path or the JAVA_HOME variable in your environment setting. You know that right ?

**Comment by Sawaqedf** [comment]
Would you mind telling me how to do it? Ive been searching but all I got was how to install it.

**Comment by mokun** [comment]
> Would you mind telling me how to do it? Ive been searching but all I got was how to install it.

But exactly at what step you have tried and you still run into trouble ?

If you can dedicate your machine to run Java 17 only, you can follow the step by steps detail in that README.md file in https://github.com/mars-sim/mars-sim.

You can also see the file at https://github.com/mars-sim/mars-sim/blob/master/README.md

Please look at the section under "Windows", which is under "OS Platforms"

I've attached a snapshot below 

![image](https://user-images.githubusercontent.com/1168584/229206055-612995ec-1a05-47ec-98ab-397bfefa13ac.png)

Let us know.

**Comment by mokun** [comment]
Please also reference https://www.happycoders.eu/java/how-to-switch-multiple-java-versions-windows/

Once you understand the principles and why, it's incredibly easy to manually switch from one version of Java to the next.

I have multiple versions of Java on my laptop and I can switch between them by editing the Environment Variable.

When you associate an extension to run Java program, it will start looking for the Java VM, based on the path you have set up in the environment setting. T

he version of Java VM at the highest ordinal order will be the first being picked. It's just that simple.

**Comment by bevans2000** [comment]
> @bevans2000 Have you tried pre-v3.5.0 on Java 18-20 ?

No but good point. Will give it a try. I expect it will be fine because we've put a lot of effort into cleaning up the java17 code base.

**Comment by bevans2000** [comment]
> > @bevans2000 Have you tried pre-v3.5.0 on Java 18-20 ?
> 
> No but good point. Will give it a try. I expect it will be fine because we've put a lot of effort into cleaning up the java17 code base.

@mokun Yes 3.5.0 JAR works on Java 20 without a problem from a quick test.

**Comment by mokun** [comment]
@Sawaqedf 

I just revised the steps in README.md as below. I'll commit it as well.

#### Windows

Choose MSI version that will automatically set up the environment path correctly.

However, there are cases that the path and JAVE_HOME variables are not being configured properly.

In the command prompt, try `java -version` to see what version of Java is first being found in your specific cases. 

IN case java cannot be found or is erroneous, then follow the steps below :

1. Locate the Java installation.

2. Start a command prompt and type this `set JAVA_HOME="<java home>\bin"`.

3. Set the PATH variable to include the Java installation `set PATH="%JAVA_HOME%\bin";%PATH%`.

> Note 2 : The order of precedence inside `PATH` is crucial. The first available folder having Java
executable inside will be the one to be loaded by Windows OS.

> Note 2a : The `\bin` is crucial. When running `java -jar xxxx.jar`, mars-sim will look for the
presence of the `java.exe` in Windows OS. If `\bin` is missing in the `JAVA_HOME` variable,
the Windows OS may not be able to locate the `java.exe` and may continue to go down the `PATH`
variable to look for a valid JDK folder. If it's not found, java cannot start mars-sim.

> Note 3 : The BEST approach is to enable only one Java build (such as Java 17.0.6)
inside `PATH` and remove all other folders referencing other java versions/builds.

4. Remove any path similar to `C:\ProgramData\Oracle\Java\javapath;`  in `PATH` variable. It can
interfere with the correct version of Java that you would like to use.

> Note 4 : Depending on the order of precedence in Path variable,
`C:\ProgramData\Oracle\Java\javapath` can load the undesired version of jre/jdk,
instead of the java version you prefer.

5. To test the version of Java that your machine is using, type "java -version"
in a command prompt window.

6. It's possible for a machine to have multiple versions of Java installed.
To check if a particular Oracle version of Java is being *enabled*,
start [Java Control Panel (JCP)](https://www.java.com/en/download/help/win_controlpanel.html)
from the Control Panel as follows :

* Move your mouse to the magnifier icon (the 2nd icon from the left) on win 10 task bar.
* Type `Configure Java`.
* Hover your mouse over the `Configure Java` and click to start the `Java Control Panel`.
* Click on `Java` tab on top.
* Click on `View` button to open up another panel window.
* Click on the checkbox on the `Enable` column to enable or disable any installed versions of Java.

> Note 5 : In JCP, each row represents a version of Java. Unfortunately, this panel
only tracks the official Oracle versions. If you install any openJDK's on
your machine, JCP won't be able to recognize them.

7. To track what versions of openjdk have been installed on your machine, you may try using 
[JDKMon](https://harmoniccode.blogspot.com/2021/04/friday-fun-lxiii-jdkmon.html).

**Comment by Sawaqedf** [comment]
Update, I tried downloading Mars on a different computer, another windows, and it worked perfectly. I mean, I didn't have time to test it out but it opened just fine. All that trouble was because of the NCH software. Thanks for your help guys, I appreciate it.
