### ISSUE TITLE
Need to keep a record of the vehicle being used for a previous mission

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#855]
**Describe the bug**
- After completing or aborting a mission, the Vehicle instance dropped out of Mission. 
- Therefore, player has to make an educated guess on which vehicle being tapped for that previous mission.

**Expected and unexpected behavior**
- All mission should keep a string record of the vehicle being used.
- Mission Tool and Monitor Tool should be able to report the name of the vehicle being used. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/232909669-2391654c-44a5-4736-b413-06f5ff10c09f.png)

![image](https://user-images.githubusercontent.com/1168584/232910495-cbc8136d-a2ac-4fe7-956c-da25541ec49b.png)

**Specifications  (please complete the following information)**
 - pre 3.6.0 build 7957 
 
**Additional context**
- May simply need to save the vehicle's name as a string

**Comment by mokun** [comment]
@bevans2000 

I suppose in the past when we make the vehicle instance stay with that previous mission, it also show the names of the previous occupants onboard and what they were doing.

This looked very wrong because the Info tab  would show Alan is eating in a lounge in the Mission Tool in that table 

As a result, we removed the Team Member table as well as the Vehicle instance.

We could create a BRAND NEW tab showcasing what the team members are currently doing before and during the mission.

In this tab, we can use a tree control structure to show clearly the position of each member in a mission.

Currently, all members are doing the same things, more or less. I don't think we even have an designated driver. 

Q : Should we brainstorm further on giving each member a dedicated/temporary position for each mission ?

**Comment by bevans2000** [comment]
The proposal for the generic Project does say each Member has a role in the project.

**Comment by mokun** [comment]
See screenshot below. What a waste to go all the way out there and find no valuable regolith-B, regolith-C, regolith-D. 

It should at least scoop up the regular type of regolith if no special regolith types are found  

![image](https://user-images.githubusercontent.com/1168584/233796863-0744dd8b-a35b-438f-b418-810a97a57949.png)

Beside keeping an string name of the vehicle, we also need to update its phase when a mission is completed. The screenshot shows that the phase hasn't been updated for a while. Should it update to at least traveling or disembarking ?

**Comment by mokun** [comment]
@bevans2000 

So I will leave this issue of missing the vehicle instance to you as you are working on `Project` and so I probably should NOT touch any of these class having to do with mission.

**Comment by bevans2000** [comment]
Yes i will look at it. I'm thinking that we keep the reference to the Vehicle but recognise that the Mission is complete. But I think the Vehicle should keep a link to the assigned Mission because currently it have to scan all active Missions to find if it is assigned to a Mission. Quite  inefficient

**Comment by bevans2000** [comment]
This has proved bigger than I expected but I think I'm there now, just doing some tests. Busy at work so struggling for free time as well.
The ```Vehicle``` now holds a reference to its Mission. This is a big performance improvement because it removes the need to search active Missions for a matching Vehicle. The problem I've had is getting logic correct to release the Mission from the vehicle. There was no central place for this to be done. 
 The Mission always retains the reference to the Vehicle.

**Comment by mokun** [comment]
> The Mission always retains the reference to the Vehicle.

Do you mean that was done in the past and will continue to do so ?
