### ISSUE TITLE
How to add commander's high priority tasks for a settlement

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#908]
**Is your feature request related to a problem? Please describe.**
- The player commander is interested in constructing a building.
- The first construction phase is constructing a foundation.
- To pour a foundation, it needs, say 80 kg, concrete.
- However, the concrete demand is only 490 and no one is automatically Digging Local Regolith.
- If player can emphasize the need for the whole settlement to get on the task of Digging Local Regolith, it won't have issues getting enough regolith to mix concrete in near future.

**Describe the rationale**
- Player lacks the ability to post tasks or customize the task priority of the settlement 

**Describe the solution you desire to see**
- Direct the player to use Command Dashboard's resource tab
- In resource tab, build an UI control so that the player may adjust the **push** points (say from -3.0 to +3.0) on his top five priority task  

**Describe alternatives you've considered**
- Use Monitor Tool's Task backlog
- Add an UI control to allow player to add a task to the list and/or adjust the priority score of this task

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/d346f866-7cc3-49f0-898c-fdcbe2a3102b)

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8145

**Additional context**
- It's also very important to be more transparent and reveal to player what priority (in terms of showcasing scores) the settlement has in what tasks and missions are more likely to do.
- For instance, under each space agency's mission agenda, there are particular push for certain science subjects and certain missions.

**Comment by mokun** [comment]
@bevans2000 

How would you enable a player commander to adjust the weight of certain tasks to take place in a settlement ?

**Comment by bevans2000** [comment]
Two things. Firstly the demand calculation may be wrong and in your example above it should have a higher value.

I would look to define a "weights" ability to the Settlement class. Then when scoring Task in the TaskMeta classes a weight can be applied to the Task score. Weights greater than 1 obviously become a multiplier. But I would look to define the weights as a Map<WeightKey,Double> and not explicitly use any Task property. Then we could use the weights for many things but just have a single table, e.g. for Missions as well. We could potentially create a dedicated ```WeightKey``` class containing a tuple of _key type_ & _key name_. where key type is Mission, Type, Trading etc etc. You get the idea. 
Use the TaskMeta name as the key in this situation.
Then add a new Tab to the Settlement UI that maintains/displays the weight. When adding offer the user a list of OnShift Tasks. There is no point showing the OffShift Task since these are about Persons/Robots having "me" time.

Sounds a nice feature to influence how a Settlement behaves and is reusable elsewhere.

Potentially, could pre-fill the weights based on the Objectives of the Reporting Authority. Now that is cool.

**Comment by mokun** [comment]
> Firstly the demand calculation may be wrong and in your example above it should have a higher value.

I've plowed through the supply chain to find out why concrete is not being produced in the last couple commits.

It works reasonably well now in response to constructing foundation.

Still the concept of having commander's high priority tasks would be a great addition in near future.

> Use the TaskMeta name as the key in this situation.

For now, I use assignTask() in BuildingConstructionMission to add a task to a person. It's not a good way.

RoverMission is using assignTask() as well.

Can you show me how to implement your approach in RoverMission and/or BuildingConstructionMission ?

**Comment by bevans2000** [comment]
> Is it also possible to post the DigLocalRegolith and DigLocalIce to task backlog ?

Yes, good idea. It is a Settlement based score so a good match. I'll do it under the control of #910

**Comment by bevans2000** [comment]
> For now, I use assignTask() in BuildingConstructionMission to add a task to a person. It's not a good way.
> 
> RoverMission is using assignTask() as well.
>

Assigning a Task directly to a Worker as part of the Mission is fine. THe Worker would not be calling the Mission methods if they have a Task already assigned.

> Can you show me how to implement your approach in RoverMission and/or BuildingConstructionMission ?

Sure, why don't I try and put something together tonight/tomorrow. I can put #890 on hold; a change would be good as that is hard going.

**Comment by bevans2000** [comment]
We can combine the science and mission modifiers on the ReportingAuthority into this same single solution. This will have the advantage of all these being editable as well. 
Secondly, the enabled Mission flags in Settlement can be handled by the logic, setting the weight to zero will disable the mission for that Settlement.
I've got a simple version working and need to add an editable UI screen

**Comment by mokun** [comment]
> Secondly, the enabled Mission flags in Settlement can be handled by the logic, setting the weight to zero will disable the mission for that Settlement.

But say we define the base score as non-sero. Then when we modify this score by multiplication, it won't result in zero.

Say if the base score is 1, and your modifier is 0.5. Then 1 x 0.5 is 0.5

**Comment by mokun** [comment]
> I've got a simple version working and need to add an editable UI screen

Can we add this to under one of 7 division tabs in Command Dashboard ?

**Comment by bevans2000** [comment]
We could but it is per Settlement and prefilled according to the objective of the Reporting Authority.

**Comment by mokun** [comment]
@bevans2000

This tab is awesome. I'm playing with the modifier score below for "Digging Local Ice" TASK : 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/11c88960-ab82-4c5e-a546-348eb52f327a)

@Urwumpe How do you like this new UI ?

I was gonna say one thing I'll like to see in future is to clearly disclose to players how each MISSION/TASK/SCIENCE score is computed. 

And we know this sort of transparency is needed and highly desired in strategy games out there. 

For instance, say the birth rate of a city is -0.7. Why would it be negative ? That means people in this city won't give birth to babies and it would be disaster for growth. So the player would like to know how this composite penalty score of -0.7 is computed. 

It turns out 
1. the city only allocates 80% of funding (thus -0.2; say, each 1% is -0.01 penalty) for the medical category needs of this city.
2. the road to medical clinic is broken (thus -0.1) in this city.
3.  the city only has one clinic while there are 10,000 population. Say each 2,000 pop needs one clinic. So it's missing 4 clinics and thus the penalty of -0.4 (=4 * -0.1) 

Similarly, we could show in the detail breakdown of each row of score with a short individual reason with a sub-score in the form of tooltip or other UI elements.

Can we do that ?

**Comment by Urwumpe** [comment]
> Can we do that ?

I first want to say "Hell, no!". Sorry. 

Especially since attribution science is one of the hardest and interpretation rich sciences in the world.

Thinking a bit further, maybe we can simplify things in our simulated world enough to "gamify" it. I have no good answer there yet, but for now, maybe the following idea is not as crazy as it sounds. 

1. There are multiple different approaches to write a study, which are limited by the field of science. Social sciences vs natural sciences vs engineering...
2. The scientist picks one approach for a new study.
3. Depending on approach, there can be one or more data sources.
4. Also there are one or more methods to interact with the data sources
5. There are also methods that turn objects (e.g. soil samples, interviews with settlers) into data sources, which might be the usage of certain tools
6. The data sources have an interface that fits to the method
7. Methods can create new derived data sources
8. Data sources can be interpreted according to models/theories/collaries/etc.
9. Interpretations on input data and derived data can classify these and with a interpretations of the results turned into a new theory/model.
10. Models can be tested by other science projects, especially if there might be different methods/tools available to produce the same kind of data source used.
11. Still a lot of magic happening there, this is no good algorithm.

**Comment by mokun** [comment]
> Especially since attribution science is one of the hardest and interpretation rich sciences in the world.

**Comment by Urwumpe** [comment]
> > Especially since attribution science is one of the hardest and interpretation rich sciences in the world.
> 
> So you're referring to Mars' weather/climate change ?!
> 
> Or you mean how settlers are supposed to support pure scientific pursuit and ignore all the political pressure from commanders or mission control of space agencies ?

You are one step ahead of me. 

Actually I mean: Telling that a certain change has a clear root cause. Like creating a fishbone diagram and interpreting it.

**Comment by bevans2000** [comment]
> @bevans2000
> 
> It's awesome ! Thanks for creating this panel tab in Settlement Unit Window.
> 

Glad you like it. I feel it consolidates and cleans up a few different areas into a single approach. And it uses the the ReportingAuthority to load it to start with which I like.
Plus I've done it so we could add other types later.
