### ISSUE TITLE
Cache the martian timestamp format 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#917]
**Is your feature request related to a problem? Please describe.**
- The Martian timestamp in stacktrace is being created with calling string.format() in each frame 
- May "cache this format" to save processing of recreating the timestamp as text as the note said within the method getMarsTimestamp()

```java
	/**
	 * Returns the Martian timestamp.
	 * 
	 * @return
	 */
    private static String getMarsTimestamp() {
    	double millisols = marsClock.getTotalMillisols();
		// Let's cache the format to save processing of recreating the timestamp as text
		if ((lastMarsTimestamp == null) || (lastClock != millisols)) {
			lastClock = millisols;
			lastMarsTimestamp = MarsClockFormat.getDateTimeStamp(marsClock);
		}
		
		return lastMarsTimestamp;
	}
```

**Describe the rationale**
-  Optimal this method by saving the processing time of recreating the timestamp as text 

**Related Classes**
- MarsClockFormat
- SimuLoggingFormatter

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8182

**Comment by bevans2000** [comment]
This relates to #650. If we make a ```MarsTime``` class that is immutable then we can cache the string inside that.

**Comment by mokun** [comment]
That's nice. Will the advantage of having immutable MarsTime be offset by the classes/,ethos that need to call MarsClock currently ? 

May be we don't need to make those MarsClock callings at all since those can be replaced with calling MasterClock ?

**Comment by bevans2000** [comment]
I want to apply the same pattern I did for the Earth time where I replaced it with standard Java Date class. The MasterClock is the only dynamic object that changes and it provides access to the current time. So we no longer have static references to MarsClock.
To minimise the impact I am going to firstly create a ```MarsTime``` class the is immutable. This is the logic of MarsClock but with no changes allowed. Creating a new class is best because it ensure there are no references to the old code. Then once MarsTime is immutable; we no longer have to keep creating copies of the MarsClock; an instance of MarsTime can be shared because it will never change. Hence; this issue becomes easy to implement.

We have too many static references already; it's a known anti-pattern of good design.
