### ISSUE TITLE
Now issues in mars-sim-network 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#92]
After commenting out the construction site test it all worked perfectly for that stage but we seem to have now errors at mars-sim-network specifically in multiplayer it seems -

See https://paste.debian.net/1046795/ for more info. 

The detailed output is from running - 
`
mvn -e -X package`

I also saw this, dunno if this is pertinent to our issue/issues or not. 

https://blog.takipi.com/how-java-10-will-change-the-way-you-code/

and these - 

https://dzone.com/articles/features-of-java-11
https://dzone.com/articles/javafx-on-jdk-11
https://dzone.com/articles/java-modularity-a-personal-journey

Have also shared how openjfx looks in my distro. 

https://paste.debian.net/1046816/

**Comment by mokun** [comment]
One of those articles talked about how Java 10 introduces a new feature called `Local Variable Type Inference`. 

It let programmers use the ‘var’ keyword rather than requiring the explicit specification of the type of the variable, such as `String`, `boolean`, `int`.

Having said that, we don't have to use it.

One real issue is the fact that openjdk 11 is separated from openjfx 11. 

There are two ways to include openjfx 11 in mars-sim. One is using maven dependency. The other is manually downloading and adding openjfx's binaries directly on the module path.

I'm trying out both approaches but they don't work yet. I believe it has to do with the Eclipse IDE or even Maven.

**Comment by mokun** [comment]
> now errors at mars-sim-network specifically in multiplayer it seems 

`mars-sim-network` requires JavaFX or openjfx.

We'll need to figure out how to configure openjfx 11 first.

**Comment by shirishag75** [comment]
right, yeah.

**Comment by mokun** [comment]
Closing this
