### ISSUE TITLE
how do I get back to Mars Net System from one of the settlements ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#99]
Once I have connected to one of the settlements, there doesn't seem a way to go back to Mars Net System or is there ?

**Comment by mokun** [comment]
It's sure that if you are connected with a particular settlement, once we type "/q", you will leave the MarsNet System and the Chat option of the Console Menu.

So does it mean that you don't mind typing "/q" twice in order to step back to the Console Menu ?

I'll refactor the logic to make it work this way.

**Comment by mokun** [comment]
Done
